import { GrammarLevel } from './types'

// GENERATED by scripts/translate-grammar.ts — reviewed and corrected by hand.
// German explanations, Spanish examples untouched. Example `en` fields hold the
// German gloss (the Block renderer shows that field as the secondary line).
// Re-running the script will NOT clobber this file's cache; delete
// scripts/.cache/grammar-de/a1-*.json to force a re-translation.
export const grammarA1De: GrammarLevel = {
  "level": "A1",
  "title": "Spanische Grammatik für Anfänger",
  "chapters": [
    {
      "id": 0,
      "title": "Alphabet, Aussprache & grundlegende Phonetik",
      "sections": [
        {
          "id": "1.1",
          "title": "Das spanische Alphabet",
          "blocks": [
            {
              "type": "text",
              "content": "Das spanische Alphabet hat 27 Buchstaben. Wichtige Unterschiede zum Deutschen: der Buchstabe „ñ“ sowie Buchstaben wie „h“ (immer stumm), „v“/„b“ (gleicher Laut) und „c“/„z“/„s“ (regional unterschiedliche Aussprache)."
            },
            {
              "type": "rules",
              "items": [
                "„h“ ist immer stumm: „hola“ wird „ola“ ausgesprochen",
                "„ll“ und „y“ klingen ähnlich (wie das deutsche „j“ in „ja“)",
                "„j“ und „g“ (vor e/i) klingen wie ein hartes „ch“ in „Bach“",
                "Ohne Akzent gilt: Wörter auf Vokal, -n oder -s werden auf der vorletzten Silbe betont, alle anderen auf der letzten"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Hola, me llamo Ana.",
                  "en": "Hallo, ich heiße Ana."
                },
                {
                  "es": "La jirafa es un animal.",
                  "en": "Die Giraffe ist ein Tier."
                }
              ]
            }
          ]
        },
        {
          "id": "1.2",
          "title": "Betonung und geschriebene Akzente",
          "blocks": [
            {
              "type": "text",
              "content": "Geschriebene Akzente (tildes) markieren die Betonung und unterscheiden gleich klingende Wörter."
            },
            {
              "type": "rules",
              "items": [
                "Wörter, die auf einen Vokal, -n oder -s enden, werden auf der vorletzten Silbe betont: casa, hablan, lunes",
                "Wörter, die auf einen anderen Konsonanten enden, werden auf der LETZTEN Silbe betont: hablar, ciudad, español",
                "Akzente auf Frage-/Ausrufewörtern: qué, cómo, dónde, cuándo, quién, cuánto",
                "Akzente unterscheiden: tú (du) vs. tu (dein), él (er) vs. el (der), sí (ja) vs. si (wenn)"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¿Cómo te llamas?",
                  "en": "Wie heißt du?"
                },
                {
                  "es": "Él tiene tu libro.",
                  "en": "Er hat dein Buch."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 1,
      "title": "Substantive und Artikel",
      "sections": [
        {
          "id": "2.1",
          "title": "Grammatisches Genus — Maskuline und feminine Substantive",
          "blocks": [
            {
              "type": "text",
              "content": "Jedes spanische Substantiv hat ein grammatisches Genus: maskulin oder feminin. Artikel, Adjektive und Pronomen müssen übereinstimmen."
            },
            {
              "type": "rules",
              "items": [
                "Die meisten Substantive, die auf -o enden, sind maskulin: el libro (das Buch), el niño (der Junge)",
                "Die meisten Substantive, die auf -a enden, sind feminin: la casa (das Haus), la niña (das Mädchen)",
                "Ausnahmen: el día (Tag), el mapa (Landkarte) — maskulin trotz der Endung -a; la mano (Hand), la foto — feminin trotz der Endung -o",
                "Substantive, die auf -ión, -dad, -tad, -tud, -umbre enden, sind meistens feminin: la nación, la ciudad",
                "Substantive, die auf -or, -aje enden, sind meistens maskulin: el color, el viaje"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "El perro es grande.",
                  "en": "Der Hund ist groß."
                },
                {
                  "es": "La ciudad es bonita.",
                  "en": "Die Stadt ist schön."
                },
                {
                  "es": "El problema es difícil.",
                  "en": "Das Problem ist schwierig."
                }
              ]
            }
          ]
        },
        {
          "id": "2.2",
          "title": "Pluralbildung",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "Substantive, die auf einen Vokal enden → füge -s hinzu: libro → libros, casa → casas",
                "Substantive, die auf einen Konsonanten enden → füge -es hinzu: ciudad → ciudades, color → colores",
                "Substantive, die auf -z enden → ändere z zu c und füge -es hinzu: lápiz → lápices",
                "Substantive, die auf einen betonten Vokal + Konsonant enden, können den Akzent verlieren: nación → naciones"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Tengo dos libros.",
                  "en": "Ich habe zwei Bücher."
                },
                {
                  "es": "Hay muchas ciudades bonitas.",
                  "en": "Es gibt viele schöne Städte."
                }
              ]
            }
          ]
        },
        {
          "id": "2.3",
          "title": "Bestimmte Artikel — el, la, los, las",
          "blocks": [
            {
              "type": "text",
              "content": "Wird verwendet, wenn man sich auf etwas Bestimmtes oder bereits Bekanntes bezieht."
            },
            {
              "type": "table",
              "headers": [
                "",
                "Maskulin",
                "Feminin"
              ],
              "rows": [
                [
                  "Singular",
                  "el",
                  "la"
                ],
                [
                  "Plural",
                  "los",
                  "las"
                ]
              ]
            },
            {
              "type": "text",
              "content": "„el“ wird vor femininen Substantiven verwendet, die mit einem betonten a-/ha- beginnen: el agua, el hacha (aber: las aguas)"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "El gato duerme.",
                  "en": "Die Katze schläft."
                },
                {
                  "es": "La profesora habla español.",
                  "en": "Die Lehrerin spricht Spanisch."
                },
                {
                  "es": "Los niños juegan en el parque.",
                  "en": "Die Kinder spielen im Park."
                },
                {
                  "es": "Las manzanas son rojas.",
                  "en": "Die Äpfel sind rot."
                }
              ]
            }
          ]
        },
        {
          "id": "2.4",
          "title": "Unbestimmte Artikel — un, una, unos, unas",
          "blocks": [
            {
              "type": "text",
              "content": "Wird verwendet, wenn man etwas zum ersten Mal einführt oder sich auf etwas Unspezifisches bezieht."
            },
            {
              "type": "table",
              "headers": [
                "",
                "Maskulin",
                "Feminin"
              ],
              "rows": [
                [
                  "Singular",
                  "un",
                  "una"
                ],
                [
                  "Plural",
                  "unos",
                  "unas"
                ]
              ]
            },
            {
              "type": "text",
              "content": "Unbestimmte Artikel werden nach „ser“ bei Berufen weggelassen: „Soy médico“ (Ich bin Arzt), nicht „Soy un médico“"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Tengo un perro.",
                  "en": "Ich habe einen Hund."
                },
                {
                  "es": "Ella es una estudiante.",
                  "en": "Sie ist eine Studentin."
                },
                {
                  "es": "Hay unos libros en la mesa.",
                  "en": "Es liegen einige Bücher auf dem Tisch."
                }
              ]
            }
          ]
        },
        {
          "id": "2.5",
          "title": "Zusammengezogene Artikel — al und del",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "a + el = al (niemals „a el“)",
                "de + el = del (niemals „de el“)",
                "Keine Zusammenziehung bei „él“ (dem Pronomen): „Hablo de él“ (Ich spreche über ihn)"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Voy al mercado.",
                  "en": "Ich gehe zum Markt."
                },
                {
                  "es": "Es el libro del profesor.",
                  "en": "Es ist das Buch des Lehrers."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 2,
      "title": "Personalpronomen",
      "sections": [
        {
          "id": "3.1",
          "title": "Subjektpronomen",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Person",
                "Singular",
                "Plural"
              ],
              "rows": [
                [
                  "1. Person",
                  "yo (ich)",
                  "nosotros/nosotras (wir)"
                ],
                [
                  "2. Person",
                  "tú (du, informell) / usted (Sie, formell)",
                  "vosotros/vosotras (ihr, Spanien) / ustedes (Sie/ihr alle)"
                ],
                [
                  "3. Person",
                  "él (er) / ella (sie)",
                  "ellos/ellas (sie)"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "Subjektpronomen werden oft weggelassen, weil die Verbendung das Subjekt verrät: „Hablo“ = „Ich spreche“",
                "Verwende sie zur Betonung oder für Kontraste: „Yo hablo español, pero ella habla inglés.“"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Yo soy estudiante.",
                  "en": "Ich bin Student."
                },
                {
                  "es": "Ella vive en Madrid.",
                  "en": "Sie wohnt in Madrid."
                },
                {
                  "es": "Nosotros hablamos español.",
                  "en": "Wir sprechen Spanisch."
                }
              ]
            }
          ]
        },
        {
          "id": "3.2",
          "title": "Tú vs. Usted — Informelle vs. formelle Anrede",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "tú — verwendet bei Freunden, Familie, Gleichaltrigen, Kindern (informell)",
                "usted (abgekürzt Ud.) — verwendet bei Fremden, älteren Menschen, Respektspersonen, im beruflichen Kontext (formell)",
                "vosotros — verwendet in Spanien für das informelle Plural-„ihr“",
                "ustedes — verwendet in Lateinamerika für die Anrede im Plural (formell und informell)"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¿Cómo te llamas?",
                  "en": "Wie heißt du? (informell)"
                },
                {
                  "es": "¿Cómo se llama usted?",
                  "en": "Wie heißen Sie? (formell)"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 3,
      "title": "Die Verben „ser“ und „estar“ (sein)",
      "sections": [
        {
          "id": "4.1",
          "title": "Ser — Dauerhafte / inhärente Eigenschaften",
          "blocks": [
            {
              "type": "text",
              "content": "„Ser“ drückt Identität, Herkunft, Nationalität, Beruf, Material, Beziehungen, Uhrzeit und inhärente Eigenschaften aus."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Konjugation"
              ],
              "rows": [
                [
                  "yo",
                  "soy"
                ],
                [
                  "tú",
                  "eres"
                ],
                [
                  "él/ella/usted",
                  "es"
                ],
                [
                  "nosotros",
                  "somos"
                ],
                [
                  "vosotros",
                  "sois"
                ],
                [
                  "ellos/ustedes",
                  "son"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "Identität/Name: „Soy Ana.“",
                "Herkunft/Nationalität: „Soy de México.“ / „Es española.“",
                "Beruf: „Ella es médica.“",
                "Material: „La mesa es de madera.“",
                "Beziehung: „Él es mi hermano.“",
                "Uhrzeit/Datum: „Son las tres.“ / „Hoy es lunes.“",
                "Körperliche Eigenschaften/Charaktereigenschaften: „Él es alto.“ / „Ella es simpática.“"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Soy estudiante de español.",
                  "en": "Ich bin Spanischstudent."
                },
                {
                  "es": "Somos de Colombia.",
                  "en": "Wir sind aus Kolumbien."
                },
                {
                  "es": "Hoy es martes, 5 de marzo.",
                  "en": "Heute ist Dienstag, der 5. März."
                }
              ]
            }
          ]
        },
        {
          "id": "4.2",
          "title": "Estar — Ort / Vorübergehende Zustände",
          "blocks": [
            {
              "type": "text",
              "content": "„Estar“ drückt Ort, vorübergehende Zustände, Bedingungen und laufende Handlungen aus."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Konjugation"
              ],
              "rows": [
                [
                  "yo",
                  "estoy"
                ],
                [
                  "tú",
                  "estás"
                ],
                [
                  "él/ella/usted",
                  "está"
                ],
                [
                  "nosotros",
                  "estamos"
                ],
                [
                  "vosotros",
                  "estáis"
                ],
                [
                  "ellos/ustedes",
                  "están"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "Ort: „El banco está en la calle mayor.“",
                "Vorübergehender Zustand/Gefühl: „Estoy cansado.“ / „Ella está triste.“",
                "Laufende Handlung (mit dem Gerundio, der Verlaufsform auf -ando/-iendo): „Estoy estudiando.“"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¿Dónde está el hotel?",
                  "en": "Wo ist das Hotel?"
                },
                {
                  "es": "Estamos en casa.",
                  "en": "Wir sind zu Hause."
                },
                {
                  "es": "El café está frío.",
                  "en": "Der Kaffee ist kalt."
                }
              ]
            }
          ]
        },
        {
          "id": "4.3",
          "title": "Ser vs. Estar — Wichtige Unterschiede",
          "blocks": [
            {
              "type": "text",
              "content": "Viele Adjektive ändern ihre Bedeutung, je nachdem, ob sie mit ser oder estar verwendet werden."
            },
            {
              "type": "table",
              "headers": [
                "Adjektiv",
                "Mit ser",
                "Mit estar"
              ],
              "rows": [
                [
                  "bueno",
                  "Es bueno. (Er ist ein guter Mensch.)",
                  "Está bueno. (Es schmeckt gut.)"
                ],
                [
                  "malo",
                  "Es malo. (Er ist schlecht/böse.)",
                  "Está malo. (Er ist krank.)"
                ],
                [
                  "aburrido",
                  "Es aburrido. (Es ist langweilig.)",
                  "Está aburrido. (Er ist gelangweilt.)"
                ],
                [
                  "listo",
                  "Es listo. (Er ist schlau.)",
                  "Está listo. (Er ist fertig.)"
                ],
                [
                  "seguro",
                  "Es seguro. (Es ist sicher.)",
                  "Está seguro. (Er ist sich sicher.)"
                ]
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 4,
      "title": "Regelmäßige und unregelmäßige Verben im Presente (Präsens)",
      "sections": [
        {
          "id": "5.1",
          "title": "Regelmäßige -AR-Verben",
          "blocks": [
            {
              "type": "text",
              "content": "Die häufigste Verbgruppe. Entferne -ar und füge die Endungen hinzu."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Endung"
              ],
              "rows": [
                [
                  "yo",
                  "-o"
                ],
                [
                  "tú",
                  "-as"
                ],
                [
                  "él/ella/usted",
                  "-a"
                ],
                [
                  "nosotros",
                  "-amos"
                ],
                [
                  "vosotros",
                  "-áis"
                ],
                [
                  "ellos/ustedes",
                  "-an"
                ]
              ]
            },
            {
              "type": "text",
              "content": "Häufige Verben: hablar (sprechen), trabajar (arbeiten), estudiar (lernen/studieren), caminar (gehen), escuchar (hören), mirar (schauen), bailar (tanzen), comprar (kaufen)"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Yo hablo español todos los días.",
                  "en": "Ich spreche jeden Tag Spanisch."
                },
                {
                  "es": "Ella trabaja en un banco.",
                  "en": "Sie arbeitet in einer Bank."
                },
                {
                  "es": "Nosotros estudiamos mucho.",
                  "en": "Wir lernen viel."
                }
              ]
            }
          ]
        },
        {
          "id": "5.2",
          "title": "Regelmäßige -ER-Verben",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Person",
                "Endung"
              ],
              "rows": [
                [
                  "yo",
                  "-o"
                ],
                [
                  "tú",
                  "-es"
                ],
                [
                  "él/ella/usted",
                  "-e"
                ],
                [
                  "nosotros",
                  "-emos"
                ],
                [
                  "vosotros",
                  "-éis"
                ],
                [
                  "ellos/ustedes",
                  "-en"
                ]
              ]
            },
            {
              "type": "text",
              "content": "Häufige Verben: comer (essen), beber (trinken), leer (lesen), aprender (lernen), vender (verkaufen), correr (rennen)"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Como una manzana.",
                  "en": "Ich esse einen Apfel."
                },
                {
                  "es": "¿Bebes café o té?",
                  "en": "Trinkst du Kaffee oder Tee?"
                },
                {
                  "es": "Aprendemos mucho en clase.",
                  "en": "Wir lernen viel im Unterricht."
                }
              ]
            }
          ]
        },
        {
          "id": "5.3",
          "title": "Regelmäßige -IR-Verben",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Person",
                "Endung"
              ],
              "rows": [
                [
                  "yo",
                  "-o"
                ],
                [
                  "tú",
                  "-es"
                ],
                [
                  "él/ella/usted",
                  "-e"
                ],
                [
                  "nosotros",
                  "-imos"
                ],
                [
                  "vosotros",
                  "-ís"
                ],
                [
                  "ellos/ustedes",
                  "-en"
                ]
              ]
            },
            {
              "type": "text",
              "content": "Häufige Verben: vivir (leben), escribir (schreiben), abrir (öffnen), recibir (erhalten), subir (hinaufgehen)"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Vivo en una ciudad grande.",
                  "en": "Ich wohne in einer großen Stadt."
                },
                {
                  "es": "Él escribe una carta.",
                  "en": "Er schreibt einen Brief."
                }
              ]
            }
          ]
        },
        {
          "id": "5.4",
          "title": "Unregelmäßiges Verb: Tener (haben)",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Person",
                "Konjugation"
              ],
              "rows": [
                [
                  "yo",
                  "tengo"
                ],
                [
                  "tú",
                  "tienes"
                ],
                [
                  "él/ella/usted",
                  "tiene"
                ],
                [
                  "nosotros",
                  "tenemos"
                ],
                [
                  "vosotros",
                  "tenéis"
                ],
                [
                  "ellos/ustedes",
                  "tienen"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "tener + Alter: „Tengo veinte años.“ (Ich bin zwanzig Jahre alt.)",
                "tener hambre/sed — hungrig/durstig sein",
                "tener frío/calor — frieren/schwitzen (mir ist kalt/warm)",
                "tener miedo — Angst haben",
                "tener razón — Recht haben",
                "tener sueño — müde sein",
                "tener prisa — in Eile sein"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¿Cuántos años tienes?",
                  "en": "Wie alt bist du?"
                },
                {
                  "es": "Tengo hambre. ¿Y tú?",
                  "en": "Ich habe Hunger. Und du?"
                }
              ]
            }
          ]
        },
        {
          "id": "5.5",
          "title": "Unregelmäßiges Verb: Ir (gehen)",
          "blocks": [
            {
              "type": "text",
              "content": "Völlig unregelmäßig. Wird auch verwendet, um die nahe Zukunft zu bilden."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Konjugation"
              ],
              "rows": [
                [
                  "yo",
                  "voy"
                ],
                [
                  "tú",
                  "vas"
                ],
                [
                  "él/ella/usted",
                  "va"
                ],
                [
                  "nosotros",
                  "vamos"
                ],
                [
                  "vosotros",
                  "vais"
                ],
                [
                  "ellos/ustedes",
                  "van"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Voy al supermercado.",
                  "en": "Ich gehe in den Supermarkt."
                },
                {
                  "es": "¿Adónde vas?",
                  "en": "Wohin gehst du?"
                },
                {
                  "es": "¡Vamos!",
                  "en": "Gehen wir!"
                }
              ]
            }
          ]
        },
        {
          "id": "5.6",
          "title": "Unregelmäßiges Verb: Hacer (tun / machen)",
          "blocks": [
            {
              "type": "text",
              "content": "Unregelmäßig nur in der yo-Form im Presente. Wird auch für das Wetter verwendet: „Hace frío.“ (Es ist kalt.) / „Hace sol.“ (Es ist sonnig.)"
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Konjugation"
              ],
              "rows": [
                [
                  "yo",
                  "hago"
                ],
                [
                  "tú",
                  "haces"
                ],
                [
                  "él/ella/usted",
                  "hace"
                ],
                [
                  "nosotros",
                  "hacemos"
                ],
                [
                  "vosotros",
                  "hacéis"
                ],
                [
                  "ellos/ustedes",
                  "hacen"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Hago ejercicio por la mañana.",
                  "en": "Ich mache morgens Sport."
                },
                {
                  "es": "¿Qué haces los fines de semana?",
                  "en": "Was machst du am Wochenende?"
                }
              ]
            }
          ]
        },
        {
          "id": "5.7",
          "title": "Unregelmäßiges Verb: Dar (geben)",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Person",
                "Konjugation"
              ],
              "rows": [
                [
                  "yo",
                  "doy"
                ],
                [
                  "tú",
                  "das"
                ],
                [
                  "él/ella/usted",
                  "da"
                ],
                [
                  "nosotros",
                  "damos"
                ],
                [
                  "vosotros",
                  "dais"
                ],
                [
                  "ellos/ustedes",
                  "dan"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Le doy el libro a la profesora.",
                  "en": "Ich gebe der Lehrerin das Buch."
                },
                {
                  "es": "¿Me das tu número de teléfono?",
                  "en": "Gibst du mir deine Telefonnummer?"
                }
              ]
            }
          ]
        },
        {
          "id": "5.8",
          "title": "Verben mit Stammwechsel (e → ie)",
          "blocks": [
            {
              "type": "text",
              "content": "Der Stammvokal „e“ wird in allen Formen außer nosotros und vosotros zu „ie“."
            },
            {
              "type": "text",
              "content": "Häufige Verben: querer (wollen/lieben), entender (verstehen), preferir (bevorzugen), empezar (anfangen), pensar (denken)"
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Querer"
              ],
              "rows": [
                [
                  "yo",
                  "quiero"
                ],
                [
                  "tú",
                  "quieres"
                ],
                [
                  "él/ella/usted",
                  "quiere"
                ],
                [
                  "nosotros",
                  "queremos"
                ],
                [
                  "vosotros",
                  "queréis"
                ],
                [
                  "ellos/ustedes",
                  "quieren"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Quiero un café, por favor.",
                  "en": "Ich möchte einen Kaffee, bitte."
                },
                {
                  "es": "Ella prefiere el té.",
                  "en": "Sie bevorzugt Tee."
                },
                {
                  "es": "La clase empieza a las nueve.",
                  "en": "Der Unterricht beginnt um neun Uhr."
                }
              ]
            }
          ]
        },
        {
          "id": "5.9",
          "title": "Verben mit Stammwechsel (o → ue)",
          "blocks": [
            {
              "type": "text",
              "content": "Der Stammvokal „o“ wird in allen Formen außer nosotros und vosotros zu „ue“."
            },
            {
              "type": "text",
              "content": "Häufige Verben: poder (können), dormir (schlafen), volver (zurückkehren), costar (kosten), encontrar (finden), jugar (u → ue)"
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Poder"
              ],
              "rows": [
                [
                  "yo",
                  "puedo"
                ],
                [
                  "tú",
                  "puedes"
                ],
                [
                  "él/ella/usted",
                  "puede"
                ],
                [
                  "nosotros",
                  "podemos"
                ],
                [
                  "vosotros",
                  "podéis"
                ],
                [
                  "ellos/ustedes",
                  "pueden"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¿Puedes ayudarme?",
                  "en": "Kannst du mir helfen?"
                },
                {
                  "es": "No puedo dormir.",
                  "en": "Ich kann nicht schlafen."
                },
                {
                  "es": "¿Cuánto cuesta?",
                  "en": "Wie viel kostet es?"
                }
              ]
            }
          ]
        },
        {
          "id": "5.10",
          "title": "Verben mit Stammwechsel (e → i)",
          "blocks": [
            {
              "type": "text",
              "content": "Der Stammvokal „e“ wird zu „i“. Nur bei -ir-Verben."
            },
            {
              "type": "text",
              "content": "Häufige Verben: pedir (bitten/bestellen), seguir (folgen/weitermachen), repetir (wiederholen), servir (bedienen/servieren)"
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Pedir"
              ],
              "rows": [
                [
                  "yo",
                  "pido"
                ],
                [
                  "tú",
                  "pides"
                ],
                [
                  "él/ella/usted",
                  "pide"
                ],
                [
                  "nosotros",
                  "pedimos"
                ],
                [
                  "vosotros",
                  "pedís"
                ],
                [
                  "ellos/ustedes",
                  "piden"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Pido una ensalada.",
                  "en": "Ich bestelle einen Salat."
                },
                {
                  "es": "Él siempre pide la cuenta.",
                  "en": "Er bittet immer um die Rechnung."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 5,
      "title": "Reflexive Verben",
      "sections": [
        {
          "id": "6.1",
          "title": "Reflexive Verben und tägliche Routinen",
          "blocks": [
            {
              "type": "text",
              "content": "Reflexive Verben zeigen an, dass das Subjekt die Handlung an sich selbst ausführt. Sie verwenden Reflexivpronomen, die vor dem konjugierten Verb stehen."
            },
            {
              "type": "table",
              "headers": [
                "Subjekt",
                "Pronomen"
              ],
              "rows": [
                [
                  "yo",
                  "me"
                ],
                [
                  "tú",
                  "te"
                ],
                [
                  "él/ella/usted",
                  "se"
                ],
                [
                  "nosotros",
                  "nos"
                ],
                [
                  "vosotros",
                  "os"
                ],
                [
                  "ellos/ustedes",
                  "se"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "Verwende bei Körperteilen bestimmte Artikel (keine Possessivpronomen): „Me lavo las manos“ (Ich wasche mir die Hände), NICHT „Me lavo mis manos“."
              ]
            },
            {
              "type": "text",
              "content": "Häufige reflexive Verben: llamarse (heißen), levantarse (aufstehen), acostarse (ins Bett gehen, o→ue), despertarse (aufwachen, e→ie), ducharse (duschen), lavarse (sich waschen), vestirse (sich anziehen, e→i), peinarse (sich kämmen), sentarse (sich setzen, e→ie), sentirse (sich fühlen, e→ie)"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Me llamo Carlos.",
                  "en": "Ich heiße Carlos."
                },
                {
                  "es": "Me levanto a las siete.",
                  "en": "Ich stehe um sieben Uhr auf."
                },
                {
                  "es": "Ella se ducha por la mañana.",
                  "en": "Sie duscht morgens."
                },
                {
                  "es": "Nos acostamos tarde los viernes.",
                  "en": "Wir gehen freitags spät ins Bett."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 6,
      "title": "Wichtige grammatische Strukturen",
      "sections": [
        {
          "id": "7.1",
          "title": "Hay — Es gibt",
          "blocks": [
            {
              "type": "text",
              "content": "„Hay“ ist eine unpersönliche Form von haber, die verwendet wird, um Existenz auszudrücken. Sie ist unveränderlich — dieselbe Form für Singular und Plural."
            },
            {
              "type": "rules",
              "items": [
                "Hay + unbestimmter Artikel + Substantiv: „Hay un banco cerca.“",
                "Hay + Zahl + Substantiv: „Hay tres estudiantes.“",
                "Verneinung: „No hay agua.“"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Hay un restaurante en esta calle.",
                  "en": "Es gibt ein Restaurant in dieser Straße."
                },
                {
                  "es": "¿Hay hoteles baratos aquí?",
                  "en": "Gibt es hier günstige Hotels?"
                },
                {
                  "es": "No hay problema.",
                  "en": "Es gibt kein Problem."
                }
              ]
            }
          ]
        },
        {
          "id": "7.2",
          "title": "Nahe Zukunft: Ir a + Infinitiv",
          "blocks": [
            {
              "type": "text",
              "content": "Wird verwendet, um über Pläne, Absichten und zukünftige Ereignisse zu sprechen."
            },
            {
              "type": "rules",
              "items": [
                "Struktur: ir (konjugiert) + a + Infinitiv"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Voy a estudiar esta tarde.",
                  "en": "Ich werde heute Nachmittag lernen."
                },
                {
                  "es": "¿Qué vas a hacer el fin de semana?",
                  "en": "Was wirst du am Wochenende tun?"
                },
                {
                  "es": "Ella va a viajar a México.",
                  "en": "Sie wird nach Mexiko reisen."
                },
                {
                  "es": "Van a llegar mañana.",
                  "en": "Sie werden morgen ankommen."
                }
              ]
            }
          ]
        },
        {
          "id": "7.3",
          "title": "Verlaufsform der Gegenwart: Estar + Gerundio",
          "blocks": [
            {
              "type": "text",
              "content": "Beschreibt eine Handlung, die genau jetzt stattfindet. Das Gerundio ist die Verlaufsform auf -ando/-iendo."
            },
            {
              "type": "rules",
              "items": [
                "-ar-Verben → -ando: hablar → hablando",
                "-er/-ir-Verben → -iendo: comer → comiendo, vivir → viviendo",
                "Unregelmäßige Gerundios: leer → leyendo, ir → yendo, dormir → durmiendo"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Estoy comiendo.",
                  "en": "Ich esse gerade."
                },
                {
                  "es": "¿Qué estás haciendo?",
                  "en": "Was machst du gerade?"
                },
                {
                  "es": "Ella está estudiando para el examen.",
                  "en": "Sie lernt gerade für die Prüfung."
                }
              ]
            }
          ]
        },
        {
          "id": "7.4",
          "title": "Modalverben mit Infinitiv",
          "blocks": [
            {
              "type": "text",
              "content": "Modalverben drücken Fähigkeit, Wunsch oder Verpflichtung aus. Sie werden konjugiert, das folgende Verb steht im Infinitiv."
            },
            {
              "type": "rules",
              "items": [
                "poder (können): „Puedo hablar español.“",
                "querer (wollen): „Quiero aprender.“",
                "deber (sollen/müssen): „Debes estudiar más.“",
                "necesitar (brauchen): „Necesito ayuda.“"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¿Puedo abrir la ventana?",
                  "en": "Kann ich das Fenster öffnen?"
                },
                {
                  "es": "Quiero aprender a bailar salsa.",
                  "en": "Ich möchte Salsa tanzen lernen."
                }
              ]
            }
          ]
        },
        {
          "id": "7.5",
          "title": "Tener que + Infinitiv (Verpflichtung)",
          "blocks": [
            {
              "type": "text",
              "content": "„Tener que“ + Infinitiv drückt eine Verpflichtung oder Notwendigkeit aus."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Tengo que trabajar mañana.",
                  "en": "Ich muss morgen arbeiten."
                },
                {
                  "es": "Ella tiene que estudiar más.",
                  "en": "Sie muss mehr lernen."
                },
                {
                  "es": "Tenemos que comprar comida.",
                  "en": "Wir müssen Essen kaufen."
                }
              ]
            }
          ]
        },
        {
          "id": "7.6",
          "title": "Gustar und ähnliche Verben",
          "blocks": [
            {
              "type": "text",
              "content": "„Gustar“ (mögen/gefallen) hat eine umgekehrte Struktur: Die Sache, die man mag, ist das Subjekt; die Person ist das indirekte Objekt (Dativobjekt)."
            },
            {
              "type": "rules",
              "items": [
                "Struktur: (A mí/ti/él...) + me/te/le/nos/os/les + gusta/gustan + Substantiv/Infinitiv",
                "gusta + Substantiv im Singular oder Infinitiv",
                "gustan + Substantiv im Plural",
                "Verwandte Verben: encantar (sehr mögen/lieben), doler (weh tun), molestar (stören), interesar (interessieren)"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Me gusta el fútbol.",
                  "en": "Ich mag Fußball."
                },
                {
                  "es": "¿Te gustan las películas de acción?",
                  "en": "Magst du Actionfilme?"
                },
                {
                  "es": "Le encanta bailar.",
                  "en": "Er/Sie liebt es, zu tanzen."
                },
                {
                  "es": "Me duele la cabeza.",
                  "en": "Mir tut der Kopf weh."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 7,
      "title": "Adjektive und Adverbien",
      "sections": [
        {
          "id": "8.1",
          "title": "Beschreibende Adjektive — Kongruenz in Genus und Numerus",
          "blocks": [
            {
              "type": "text",
              "content": "Adjektive müssen in Genus und Numerus mit dem Substantiv übereinstimmen, das sie beschreiben. Sie stehen im Allgemeinen nach dem Substantiv."
            },
            {
              "type": "rules",
              "items": [
                "Adjektive, die auf -o enden, verändern sich: bueno/buena/buenos/buenas",
                "Adjektive auf -e oder auf einen Konsonanten haben für Maskulin und Feminin dieselbe Form: grande, azul",
                "Nationalitätsadjektive verändern sich: español/española"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "El coche rojo.",
                  "en": "Das rote Auto."
                },
                {
                  "es": "La casa roja.",
                  "en": "Das rote Haus."
                },
                {
                  "es": "Un estudiante inteligente.",
                  "en": "Ein intelligenter Student."
                }
              ]
            }
          ]
        },
        {
          "id": "8.2",
          "title": "Stellung der Adjektive",
          "blocks": [
            {
              "type": "text",
              "content": "Die meisten Adjektive stehen nach dem Substantiv; einige stehen davor und können sich verkürzen."
            },
            {
              "type": "rules",
              "items": [
                "bueno → buen (vor maskulinem Singular): „Es un buen estudiante.“",
                "grande → gran (vor jedem Substantiv im Singular mit der Bedeutung „großartig“): „Es un gran hombre.“",
                "malo → mal, primero → primer, tercero → tercer"
              ]
            }
          ]
        },
        {
          "id": "8.3",
          "title": "Demonstrativadjektive — Este, Ese, Aquel",
          "blocks": [
            {
              "type": "text",
              "content": "Sie zeigen die Entfernung zum Sprecher an."
            },
            {
              "type": "table",
              "headers": [
                "Entfernung",
                "Maskulin Singular",
                "Feminin Singular",
                "Maskulin Plural",
                "Feminin Plural"
              ],
              "rows": [
                [
                  "Nah (dieser/diese/dieses)",
                  "este",
                  "esta",
                  "estos",
                  "estas"
                ],
                [
                  "Mittel (der/die/das da)",
                  "ese",
                  "esa",
                  "esos",
                  "esas"
                ],
                [
                  "Weit weg (jener/jene/jenes dort)",
                  "aquel",
                  "aquella",
                  "aquellos",
                  "aquellas"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Este libro es interesante.",
                  "en": "Dieses Buch ist interessant."
                },
                {
                  "es": "Ese restaurante es bueno.",
                  "en": "Dieses Restaurant da ist gut."
                },
                {
                  "es": "Aquella montaña es muy alta.",
                  "en": "Jener Berg dort drüben ist sehr hoch."
                }
              ]
            }
          ]
        },
        {
          "id": "8.4",
          "title": "Possessivadjektive",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Person",
                "Singular",
                "Plural"
              ],
              "rows": [
                [
                  "yo",
                  "mi",
                  "mis"
                ],
                [
                  "tú",
                  "tu",
                  "tus"
                ],
                [
                  "él/ella/usted",
                  "su",
                  "sus"
                ],
                [
                  "nosotros",
                  "nuestro/nuestra",
                  "nuestros/nuestras"
                ],
                [
                  "vosotros",
                  "vuestro/vuestra",
                  "vuestros/vuestras"
                ],
                [
                  "ellos/ustedes",
                  "su",
                  "sus"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "mi/tu/su richten sich NICHT nach dem Genus, nur nach dem Numerus",
                "nuestro/vuestro richten sich DOCH nach dem Genus: nuestro libro / nuestra casa"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Mi casa es grande.",
                  "en": "Mein Haus ist groß."
                },
                {
                  "es": "Nuestra profesora es simpática.",
                  "en": "Unsere Lehrerin ist nett."
                }
              ]
            }
          ]
        },
        {
          "id": "8.5",
          "title": "Mengenangaben und Intensivierer",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "mucho/a/os/as — viel/viele",
                "poco/a/os/as — wenig/wenige",
                "bastante/s — ziemlich viel/viele",
                "todo/a/os/as — ganz/alle",
                "cada — jeder (unveränderlich)",
                "muy — sehr (vor Adjektiven/Adverbien)",
                "mucho — viel / sehr (nach Verben)"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Tengo mucho trabajo.",
                  "en": "Ich habe viel Arbeit."
                },
                {
                  "es": "Esta sopa está muy buena.",
                  "en": "Diese Suppe schmeckt sehr gut."
                },
                {
                  "es": "Me gusta mucho la música.",
                  "en": "Ich mag Musik sehr."
                }
              ]
            }
          ]
        },
        {
          "id": "8.6",
          "title": "Grundlegende Adverbien",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "Zeit: hoy (heute), mañana (morgen), ayer (gestern), ahora (jetzt), siempre (immer), nunca (nie), a veces (manchmal), luego (später), pronto (bald)",
                "Ort: aquí (hier), allí (dort), cerca (in der Nähe), lejos (weit)",
                "Art und Weise: bien (gut), mal (schlecht), despacio (langsam), rápido (schnell)",
                "Adverbien auf -mente: gebildet aus dem femininen Adjektiv + -mente: rápida → rápidamente, fácil → fácilmente"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Ella siempre llega tarde.",
                  "en": "Sie kommt immer zu spät."
                },
                {
                  "es": "Habla muy despacio, por favor.",
                  "en": "Sprich bitte sehr langsam."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 8,
      "title": "Fragebildung und Verneinung",
      "sections": [
        {
          "id": "9.1",
          "title": "Fragen bilden",
          "blocks": [
            {
              "type": "text",
              "content": "Fragen stehen zwischen umgekehrtem und normalem Fragezeichen (¿...?). Die Wortstellung ist oft dieselbe wie im Aussagesatz — nur die Intonation steigt am Ende. Ein Hilfsverb wie im Englischen („do/does“) gibt es nicht."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¿Hablas español?",
                  "en": "Sprichst du Spanisch?"
                },
                {
                  "es": "¿Tienes un bolígrafo?",
                  "en": "Hast du einen Stift?"
                }
              ]
            }
          ]
        },
        {
          "id": "9.2",
          "title": "Fragewörter",
          "blocks": [
            {
              "type": "text",
              "content": "Alle Fragewörter tragen einen Akzent (tilde)."
            },
            {
              "type": "table",
              "headers": [
                "Fragewort",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "¿Qué?",
                  "Was?",
                  "¿Qué haces?"
                ],
                [
                  "¿Quién? / ¿Quiénes?",
                  "Wer?",
                  "¿Quién es ella?"
                ],
                [
                  "¿Cuál? / ¿Cuáles?",
                  "Welche(r/s)? / Was?",
                  "¿Cuál es tu nombre?"
                ],
                [
                  "¿Dónde?",
                  "Wo?",
                  "¿Dónde vives?"
                ],
                [
                  "¿Adónde?",
                  "Wohin?",
                  "¿Adónde vas?"
                ],
                [
                  "¿Cuándo?",
                  "Wann?",
                  "¿Cuándo es tu cumpleaños?"
                ],
                [
                  "¿Cómo?",
                  "Wie?",
                  "¿Cómo estás?"
                ],
                [
                  "¿Por qué?",
                  "Warum?",
                  "¿Por qué estudias español?"
                ],
                [
                  "¿Cuánto/a?",
                  "Wie viel?",
                  "¿Cuánto cuesta?"
                ],
                [
                  "¿Cuántos/as?",
                  "Wie viele?",
                  "¿Cuántos años tienes?"
                ]
              ]
            },
            {
              "type": "text",
              "content": "Verwende „qué“ mit Substantiven („¿Qué libro lees?“), verwende „cuál“, wenn du zwischen Optionen auswählst („¿Cuál es tu dirección?“)."
            }
          ]
        },
        {
          "id": "9.3",
          "title": "Verneinung",
          "blocks": [
            {
              "type": "text",
              "content": "Setze „no“ direkt vor das Verb. Doppelte Verneinungen sind im Spanischen korrekt."
            },
            {
              "type": "rules",
              "items": [
                "no — nein/nicht",
                "nada — nichts",
                "nadie — niemand",
                "nunca / jamás — nie / niemals",
                "ningún/ninguno/ninguna — kein/keine/keines",
                "tampoco — auch nicht"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "No entiendo.",
                  "en": "Ich verstehe nicht."
                },
                {
                  "es": "No tengo nada.",
                  "en": "Ich habe nichts."
                },
                {
                  "es": "Nunca llego tarde.",
                  "en": "Ich komme nie zu spät."
                },
                {
                  "es": "A mí tampoco me gusta.",
                  "en": "Mir gefällt es auch nicht."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 9,
      "title": "Präpositionen, Zahlen und Zeitangaben",
      "sections": [
        {
          "id": "10.1",
          "title": "Wichtigste Präpositionen",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Präposition",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "a",
                  "nach, zu, in, an",
                  "Voy a Madrid."
                ],
                [
                  "de",
                  "von, aus",
                  "Soy de España."
                ],
                [
                  "en",
                  "in, auf, an",
                  "Vivo en una ciudad."
                ],
                [
                  "con",
                  "mit",
                  "Voy con mi amigo."
                ],
                [
                  "sin",
                  "ohne",
                  "Café sin azúcar."
                ],
                [
                  "por",
                  "für, durch, pro",
                  "Gracias por todo."
                ],
                [
                  "para",
                  "für (Zweck/Empfänger)",
                  "Este regalo es para ti."
                ],
                [
                  "sobre",
                  "auf, über",
                  "El libro está sobre la mesa."
                ],
                [
                  "entre",
                  "zwischen",
                  "Está entre la farmacia y el banco."
                ],
                [
                  "hasta",
                  "bis",
                  "Hasta luego."
                ],
                [
                  "desde",
                  "von, seit",
                  "Vivo aquí desde enero."
                ],
                [
                  "hacia",
                  "in Richtung, nach",
                  "Camina hacia el norte."
                ]
              ]
            }
          ]
        },
        {
          "id": "10.2",
          "title": "Por vs. Para — Wichtiger Unterschied",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "Por — Dauer: „Estudié por dos horas.“",
                "Por — Austausch: „Lo compré por diez euros.“",
                "Por — Grund/Ursache: „No puedo salir por el frío.“",
                "Por — Bewegung durch: „Pasamos por el parque.“"
              ]
            },
            {
              "type": "rules",
              "items": [
                "Para — Zweck/Ziel: „Estudio para aprender.“",
                "Para — Empfänger: „Este café es para usted.“",
                "Para — Zielort: „Salgo para México mañana.“",
                "Para — Frist: „Lo necesito para el lunes.“"
              ]
            }
          ]
        },
        {
          "id": "10.3",
          "title": "Zahlen 0–100",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "0–9",
                "10–19",
                "20–29",
                "30–100"
              ],
              "rows": [
                [
                  "0 — cero",
                  "10 — diez",
                  "20 — veinte",
                  "30 — treinta"
                ],
                [
                  "1 — uno",
                  "11 — once",
                  "21 — veintiuno",
                  "40 — cuarenta"
                ],
                [
                  "2 — dos",
                  "12 — doce",
                  "22 — veintidós",
                  "50 — cincuenta"
                ],
                [
                  "3 — tres",
                  "13 — trece",
                  "23 — veintitrés",
                  "60 — sesenta"
                ],
                [
                  "4 — cuatro",
                  "14 — catorce",
                  "24 — veinticuatro",
                  "70 — setenta"
                ],
                [
                  "5 — cinco",
                  "15 — quince",
                  "25 — veinticinco",
                  "80 — ochenta"
                ],
                [
                  "6 — seis",
                  "16 — dieciséis",
                  "26 — veintiséis",
                  "90 — noventa"
                ],
                [
                  "7 — siete",
                  "17 — diecisiete",
                  "27 — veintisiete",
                  "100 — cien"
                ],
                [
                  "8 — ocho",
                  "18 — dieciocho",
                  "28 — veintiocho",
                  ""
                ],
                [
                  "9 — nueve",
                  "19 — diecinueve",
                  "29 — veintinueve",
                  ""
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "Ab 31: treinta y uno, treinta y dos usw.",
                "„Uno“ verkürzt sich vor maskulinen Substantiven zu „un“: „veintiún estudiantes“",
                "„Cien“ wird vor weiteren Zahlen zu „ciento“: „ciento uno“ (101)"
              ]
            }
          ]
        },
        {
          "id": "10.4",
          "title": "Ordinalzahlen (1.–10.)",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Ordinalzahl",
                "Maskulin",
                "Feminin"
              ],
              "rows": [
                [
                  "1.",
                  "primero (primer)",
                  "primera"
                ],
                [
                  "2.",
                  "segundo",
                  "segunda"
                ],
                [
                  "3.",
                  "tercero (tercer)",
                  "tercera"
                ],
                [
                  "4.",
                  "cuarto",
                  "cuarta"
                ],
                [
                  "5.",
                  "quinto",
                  "quinta"
                ],
                [
                  "6.",
                  "sexto",
                  "sexta"
                ],
                [
                  "7.",
                  "séptimo",
                  "séptima"
                ],
                [
                  "8.",
                  "octavo",
                  "octava"
                ],
                [
                  "9.",
                  "noveno",
                  "novena"
                ],
                [
                  "10.",
                  "décimo",
                  "décima"
                ]
              ]
            }
          ]
        },
        {
          "id": "10.5",
          "title": "Die Uhrzeit",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "„¿Qué hora es?“ — Wie spät ist es?",
                "„Es la una.“ — Es ist ein Uhr. (Singular)",
                "„Son las dos/tres/cuatro...“ — Es ist zwei/drei/vier Uhr...",
                "„Son las tres y media.“ — Halb vier.",
                "„Son las cuatro y cuarto.“ — Viertel nach vier.",
                "„Son las cinco menos cuarto.“ — Viertel vor fünf.",
                "„de la mañana“ (morgens) / „de la tarde“ (nachmittags) / „de la noche“ (abends)"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "La clase empieza a las nueve de la mañana.",
                  "en": "Der Unterricht beginnt um neun Uhr morgens."
                }
              ]
            }
          ]
        },
        {
          "id": "10.6",
          "title": "Wochentage",
          "blocks": [
            {
              "type": "text",
              "content": "lunes, martes, miércoles, jueves, viernes, sábado, domingo"
            },
            {
              "type": "rules",
              "items": [
                "Wochentage werden klein geschrieben und sind maskulin",
                "„el lunes“ = am Montag (einmalig), „los lunes“ = montags (regelmäßig)"
              ]
            }
          ]
        },
        {
          "id": "10.7",
          "title": "Monate und Datum",
          "blocks": [
            {
              "type": "text",
              "content": "enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre, octubre, noviembre, diciembre"
            },
            {
              "type": "rules",
              "items": [
                "Monate werden klein geschrieben",
                "„Hoy es el cinco de marzo.“ — Heute ist der fünfte März.",
                "Verwende Kardinalzahlen, außer „el primero“ für den 1."
              ]
            }
          ]
        },
        {
          "id": "10.8",
          "title": "Häufige Konjunktionen",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Konjunktion",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "y / e (vor i-/hi-)",
                  "und",
                  "Hablo español y francés."
                ],
                [
                  "o / u (vor o-/ho-)",
                  "oder",
                  "¿Café o té?"
                ],
                [
                  "pero",
                  "aber",
                  "Me gusta, pero es caro."
                ],
                [
                  "porque",
                  "weil",
                  "No puedo ir porque estoy enfermo."
                ],
                [
                  "que",
                  "dass / der, die, das",
                  "Creo que sí."
                ],
                [
                  "si",
                  "falls, wenn",
                  "Si tienes tiempo, llámame."
                ],
                [
                  "cuando",
                  "wenn, als",
                  "Cuando llego a casa, como."
                ]
              ]
            }
          ]
        }
      ]
    }
  ]
}
