import { GrammarLevel } from './types'

// GENERATED by scripts/translate-grammar.ts — reviewed and corrected by hand.
// German explanations, Spanish examples untouched. Example `en` fields hold the
// German gloss (the Block renderer shows that field as the secondary line).
// Re-running the script will NOT clobber this file's cache; delete
// scripts/.cache/grammar-de/a2-*.json to force a re-translation.
export const grammarA2De: GrammarLevel = {
  "level": "A2",
  "title": "Spanische Grammatik — Grundstufe",
  "chapters": [
    {
      "id": 0,
      "title": "Das Indefinido (einfache Vergangenheit)",
      "sections": [
        {
          "id": "1.1",
          "title": "Regelmäßige Verben auf -AR im Indefinido",
          "blocks": [
            {
              "type": "text",
              "content": "Das Indefinido (einfache Vergangenheit) beschreibt abgeschlossene Handlungen in der Vergangenheit zu einem bestimmten Zeitpunkt."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Endung",
                "Beispiel"
              ],
              "rows": [
                [
                  "yo",
                  "-é",
                  "hablé"
                ],
                [
                  "tú",
                  "-aste",
                  "hablaste"
                ],
                [
                  "él/ella/usted",
                  "-ó",
                  "habló"
                ],
                [
                  "nosotros/as",
                  "-amos",
                  "hablamos"
                ],
                [
                  "vosotros/as",
                  "-asteis",
                  "hablasteis"
                ],
                [
                  "ellos/ellas/ustedes",
                  "-aron",
                  "hablaron"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "Die Form von nosotros ist dieselbe wie im Presente (Präsens) — der Kontext verdeutlicht die Bedeutung.",
                "Die Formen von yo und él/ella tragen einen Akzent (tilde)."
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Ayer hablé con mi madre.",
                  "en": "Gestern habe ich mit meiner Mutter gesprochen."
                },
                {
                  "es": "Ella trabajó ocho horas.",
                  "en": "Sie hat acht Stunden gearbeitet."
                },
                {
                  "es": "Compramos pan esta mañana.",
                  "en": "Wir haben heute Morgen Brot gekauft."
                }
              ]
            }
          ]
        },
        {
          "id": "1.2",
          "title": "Regelmäßige Verben auf -ER und -IR im Indefinido",
          "blocks": [
            {
              "type": "text",
              "content": "Verben auf -ER und -IR teilen sich dieselben Endungen im Indefinido."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Endung",
                "comer",
                "vivir"
              ],
              "rows": [
                [
                  "yo",
                  "-í",
                  "comí",
                  "viví"
                ],
                [
                  "tú",
                  "-iste",
                  "comiste",
                  "viviste"
                ],
                [
                  "él/ella/usted",
                  "-ió",
                  "comió",
                  "vivió"
                ],
                [
                  "nosotros/as",
                  "-imos",
                  "comimos",
                  "vivimos"
                ],
                [
                  "vosotros/as",
                  "-isteis",
                  "comisteis",
                  "vivisteis"
                ],
                [
                  "ellos/ellas/ustedes",
                  "-ieron",
                  "comieron",
                  "vivieron"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Comí una pizza anoche.",
                  "en": "Ich habe gestern Abend eine Pizza gegessen."
                },
                {
                  "es": "¿Escribiste el correo?",
                  "en": "Hast du die E-Mail geschrieben?"
                },
                {
                  "es": "Vivieron en Barcelona dos años.",
                  "en": "Sie haben zwei Jahre in Barcelona gelebt."
                }
              ]
            }
          ]
        },
        {
          "id": "1.3",
          "title": "Unregelmäßige Verben im Indefinido: Ser / Ir",
          "blocks": [
            {
              "type": "text",
              "content": "„Ser“ und „ir“ teilen sich dieselben Formen im Indefinido. Der Kontext bestimmt die Bedeutung."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Form"
              ],
              "rows": [
                [
                  "yo",
                  "fui"
                ],
                [
                  "tú",
                  "fuiste"
                ],
                [
                  "él/ella/usted",
                  "fue"
                ],
                [
                  "nosotros/as",
                  "fuimos"
                ],
                [
                  "vosotros/as",
                  "fuisteis"
                ],
                [
                  "ellos/ellas/ustedes",
                  "fueron"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Fui al supermercado.",
                  "en": "Ich bin zum Supermarkt gegangen. (ir)"
                },
                {
                  "es": "Fue una fiesta increíble.",
                  "en": "Es war eine unglaubliche Party. (ser)"
                },
                {
                  "es": "Fuimos a la playa el domingo.",
                  "en": "Wir sind am Sonntag an den Strand gegangen. (ir)"
                }
              ]
            }
          ]
        },
        {
          "id": "1.4",
          "title": "Unregelmäßige Verben im Indefinido: Estar, Tener, Hacer, Poder, Poner, Saber, Querer, Venir, Decir, Traer",
          "blocks": [
            {
              "type": "text",
              "content": "Diese häufig verwendeten Verben haben unregelmäßige Stämme und eine besondere Gruppe unbetonter Endungen (keine Akzente bei yo oder él/ella)."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Endung"
              ],
              "rows": [
                [
                  "yo",
                  "-e"
                ],
                [
                  "tú",
                  "-iste"
                ],
                [
                  "él/ella/usted",
                  "-o"
                ],
                [
                  "nosotros/as",
                  "-imos"
                ],
                [
                  "vosotros/as",
                  "-isteis"
                ],
                [
                  "ellos/ellas/ustedes",
                  "-ieron / -eron"
                ]
              ]
            },
            {
              "type": "table",
              "headers": [
                "Infinitiv",
                "Stamm",
                "yo-Form"
              ],
              "rows": [
                [
                  "estar",
                  "estuv-",
                  "estuve"
                ],
                [
                  "tener",
                  "tuv-",
                  "tuve"
                ],
                [
                  "hacer",
                  "hic-/hiz-",
                  "hice"
                ],
                [
                  "poder",
                  "pud-",
                  "pude"
                ],
                [
                  "poner",
                  "pus-",
                  "puse"
                ],
                [
                  "saber",
                  "sup-",
                  "supe"
                ],
                [
                  "querer",
                  "quis-",
                  "quise"
                ],
                [
                  "venir",
                  "vin-",
                  "vine"
                ],
                [
                  "decir",
                  "dij-",
                  "dije"
                ],
                [
                  "traer",
                  "traj-",
                  "traje"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "„Hacer“ ändert in der Form für él/ella das c zu z: „hizo“ (damit der Zischlaut erhalten bleibt).",
                "„Decir“ und „traer“ verwenden -eron (nicht -ieron) in der Form für ellos: dijeron, trajeron."
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Estuve en casa todo el día.",
                  "en": "Ich war den ganzen Tag zu Hause."
                },
                {
                  "es": "Tuve un examen difícil.",
                  "en": "Ich hatte eine schwierige Prüfung."
                },
                {
                  "es": "Hizo mucho calor ayer.",
                  "en": "Es war gestern sehr heiß."
                },
                {
                  "es": "No pude dormir anoche.",
                  "en": "Ich konnte gestern Nacht nicht schlafen."
                },
                {
                  "es": "¿Qué dijiste?",
                  "en": "Was hast du gesagt?"
                }
              ]
            }
          ]
        },
        {
          "id": "1.5",
          "title": "Zeitangaben für das Indefinido",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Signalwort",
                "Bedeutung"
              ],
              "rows": [
                [
                  "ayer",
                  "gestern"
                ],
                [
                  "anoche",
                  "gestern Abend"
                ],
                [
                  "la semana pasada",
                  "letzte Woche"
                ],
                [
                  "el mes pasado",
                  "letzten Monat"
                ],
                [
                  "el año pasado",
                  "letztes Jahr"
                ],
                [
                  "hace dos días",
                  "vor zwei Tagen"
                ],
                [
                  "el lunes (pasado)",
                  "(letzten) Montag"
                ],
                [
                  "una vez",
                  "einmal"
                ],
                [
                  "de repente",
                  "plötzlich"
                ],
                [
                  "en ese momento",
                  "in diesem Moment"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "La semana pasada viajé a Madrid.",
                  "en": "Letzte Woche bin ich nach Madrid gereist."
                },
                {
                  "es": "Hace tres años estudié en Londres.",
                  "en": "Vor drei Jahren habe ich in London studiert."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 1,
      "title": "Das Imperfecto (Verlaufsvergangenheit)",
      "sections": [
        {
          "id": "2.1",
          "title": "Regelmäßige Verben auf -AR im Imperfecto",
          "blocks": [
            {
              "type": "text",
              "content": "Das Imperfecto beschreibt gewohnheitsmäßige, wiederholte oder andauernde Handlungen in der Vergangenheit sowie Beschreibungen und Hintergründe in der Vergangenheit."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Endung",
                "Beispiel"
              ],
              "rows": [
                [
                  "yo",
                  "-aba",
                  "hablaba"
                ],
                [
                  "tú",
                  "-abas",
                  "hablabas"
                ],
                [
                  "él/ella/usted",
                  "-aba",
                  "hablaba"
                ],
                [
                  "nosotros/as",
                  "-ábamos",
                  "hablábamos"
                ],
                [
                  "vosotros/as",
                  "-abais",
                  "hablabais"
                ],
                [
                  "ellos/ellas/ustedes",
                  "-aban",
                  "hablaban"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "Nur die nosotros-Form trägt einen Akzent (tilde)",
                "Die yo- und él/ella-Form sind identisch — der Kontext klärt es auf"
              ]
            }
          ]
        },
        {
          "id": "2.2",
          "title": "Regelmäßige Verben auf -ER und -IR im Imperfecto",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Person",
                "Endung",
                "comer",
                "vivir"
              ],
              "rows": [
                [
                  "yo",
                  "-ía",
                  "comía",
                  "vivía"
                ],
                [
                  "tú",
                  "-ías",
                  "comías",
                  "vivías"
                ],
                [
                  "él/ella/usted",
                  "-ía",
                  "comía",
                  "vivía"
                ],
                [
                  "nosotros/as",
                  "-íamos",
                  "comíamos",
                  "vivíamos"
                ],
                [
                  "vosotros/as",
                  "-íais",
                  "comíais",
                  "vivíais"
                ],
                [
                  "ellos/ellas/ustedes",
                  "-ían",
                  "comían",
                  "vivían"
                ]
              ]
            }
          ]
        },
        {
          "id": "2.3",
          "title": "Unregelmäßige Verben im Imperfecto",
          "blocks": [
            {
              "type": "text",
              "content": "Nur drei Verben sind im Imperfecto unregelmäßig."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Ser",
                "Ir",
                "Ver"
              ],
              "rows": [
                [
                  "yo",
                  "era",
                  "iba",
                  "veía"
                ],
                [
                  "tú",
                  "eras",
                  "ibas",
                  "veías"
                ],
                [
                  "él/ella/usted",
                  "era",
                  "iba",
                  "veía"
                ],
                [
                  "nosotros/as",
                  "éramos",
                  "íbamos",
                  "veíamos"
                ],
                [
                  "vosotros/as",
                  "erais",
                  "ibais",
                  "veíais"
                ],
                [
                  "ellos/ellas/ustedes",
                  "eran",
                  "iban",
                  "veían"
                ]
              ]
            }
          ]
        },
        {
          "id": "2.4",
          "title": "Verwendung des Imperfecto",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "Gewohnheitsmäßige Handlungen in der Vergangenheit: „De niño, jugaba en el parque.“ (Als Kind spielte ich immer im Park.)",
                "Beschreibungen in der Vergangenheit: „La casa era grande y tenía un jardín.“ (Das Haus war groß und hatte einen Garten.)",
                "Andauernde Handlungen: „Mientras comíamos, llovía.“ (Während wir aßen, regnete es.)",
                "Alter, Uhrzeit und Wetter in der Vergangenheit: „Tenía diez años.“ / „Eran las tres.“ / „Hacía frío.“",
                "Körperliche und emotionale Zustände: „Estaba cansado y tenía hambre.“ (Ich war müde und hatte Hunger.)"
              ]
            },
            {
              "type": "table",
              "headers": [
                "Signalwort",
                "Bedeutung"
              ],
              "rows": [
                [
                  "siempre",
                  "immer"
                ],
                [
                  "a menudo",
                  "oft"
                ],
                [
                  "todos los días",
                  "jeden Tag"
                ],
                [
                  "cada semana",
                  "jede Woche"
                ],
                [
                  "de niño/a",
                  "als Kind"
                ],
                [
                  "antes",
                  "früher / in der Vergangenheit"
                ],
                [
                  "generalmente",
                  "im Allgemeinen"
                ],
                [
                  "normalmente",
                  "normalerweise"
                ],
                [
                  "mientras",
                  "während"
                ],
                [
                  "en esa época",
                  "zu dieser Zeit"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Cuando era joven, iba a la playa todos los veranos.",
                  "en": "Als ich jung war, ging ich jeden Sommer an den Strand."
                },
                {
                  "es": "Mi abuela siempre cocinaba los domingos.",
                  "en": "Meine Großmutter kochte immer sonntags."
                },
                {
                  "es": "Eran las ocho y hacía mucho frío.",
                  "en": "Es war acht Uhr und es war sehr kalt."
                }
              ]
            }
          ]
        },
        {
          "id": "2.5",
          "title": "Indefinido vs. Imperfecto — Grundlegender Kontrast",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Indefinido",
                "Imperfecto"
              ],
              "rows": [
                [
                  "Abgeschlossene Handlung zu einem bestimmten Zeitpunkt",
                  "Andauernde oder gewohnheitsmäßige Handlung"
                ],
                [
                  "Was geschah",
                  "Was gerade im Gange war"
                ],
                [
                  "Bringt die Geschichte voran",
                  "Beschreibt Kulisse und Hintergrund"
                ],
                [
                  "Einzelnes Ereignis",
                  "Wiederholt oder andauernd"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Ayer llovió.",
                  "en": "Gestern hat es geregnet. (abgeschlossenes Ereignis)"
                },
                {
                  "es": "Ayer llovía cuando salí.",
                  "en": "Gestern regnete es gerade, als ich losging. (Hintergrund + Ereignis)"
                },
                {
                  "es": "Comí a las dos.",
                  "en": "Ich habe um zwei gegessen. (abgeschlossen)"
                },
                {
                  "es": "Siempre comía a las dos.",
                  "en": "Ich aß immer um zwei. (gewohnheitsmäßig)"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 2,
      "title": "Direkte Objektpronomen",
      "sections": [
        {
          "id": "3.1",
          "title": "Was sind direkte Objektpronomen?",
          "blocks": [
            {
              "type": "text",
              "content": "Direkte Objektpronomen ersetzen das Substantiv, das direkt das Ziel der Handlung des Verbs ist („Was?“ oder „Wen?“)."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Pronomen"
              ],
              "rows": [
                [
                  "yo",
                  "me"
                ],
                [
                  "tú",
                  "te"
                ],
                [
                  "él / usted (masc.)",
                  "lo"
                ],
                [
                  "ella / usted (fem.)",
                  "la"
                ],
                [
                  "nosotros/as",
                  "nos"
                ],
                [
                  "vosotros/as",
                  "os"
                ],
                [
                  "ellos / ustedes (masc.)",
                  "los"
                ],
                [
                  "ellas / ustedes (fem.)",
                  "las"
                ]
              ]
            }
          ]
        },
        {
          "id": "3.2",
          "title": "Regeln zur Wortstellung",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "Vor einem konjugierten Verb: „Lo veo.“ (Ich sehe es/ihn.)",
                "Am Ende eines Infinitivs angehängt: „Quiero verlo.“ (Ich möchte es sehen.)",
                "Am Ende eines Gerundio angehängt: „Estoy comiéndola.“ (Ich esse es gerade.)",
                "Am Ende eines bejahenden Befehls angehängt: „Cómelo.“ (Iss es.)",
                "Vor einem verneinten Befehl: „No lo comas.“ (Iss es nicht.)",
                "Wenn ein konjugiertes Verb + Infinitiv/Gerundio vorliegt, kann das Pronomen stattdessen vor das konjugierte Verb gestellt werden: „Lo quiero ver.“ / „La estoy comiendo.“"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¿Tienes el libro? — Sí, lo tengo.",
                  "en": "Hast du das Buch? — Ja, ich habe es."
                },
                {
                  "es": "¿Ves a María? — Sí, la veo.",
                  "en": "Siehst du Maria? — Ja, ich sehe sie."
                },
                {
                  "es": "¿Compraste las manzanas? — Sí, las compré.",
                  "en": "Hast du die Äpfel gekauft? — Ja, ich habe sie gekauft."
                },
                {
                  "es": "Voy a llamar a Pedro. — Voy a llamarlo. / Lo voy a llamar.",
                  "en": "Ich werde Pedro anrufen. — Ich werde ihn anrufen."
                }
              ]
            }
          ]
        },
        {
          "id": "3.3",
          "title": "Das personale „a“ bei direkten Objekten",
          "blocks": [
            {
              "type": "text",
              "content": "Wenn das direkte Objekt eine bestimmte Person (oder ein personifiziertes Wesen) ist, verwendest du die Präposition „a“ vor ihm."
            },
            {
              "type": "rules",
              "items": [
                "„Veo a María.“ — Ich sehe Maria. (bestimmte Person = personales a)",
                "„Veo la película.“ — Ich sehe den Film. (Sache = kein personales a)",
                "„Busco a mi hermano.“ — Ich suche meinen Bruder.",
                "„Busco un taxi.“ — Ich suche ein Taxi.",
                "Wird auch bei Haustieren verwendet: „Quiero a mi perro.“ — Ich habe meinen Hund lieb."
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 3,
      "title": "Indirekte Objektpronomen",
      "sections": [
        {
          "id": "4.1",
          "title": "Was sind indirekte Objektpronomen?",
          "blocks": [
            {
              "type": "text",
              "content": "Indirekte Objektpronomen geben an, wem oder für wen etwas getan wird („Wem?“ / „Für wen?“)."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Pronomen"
              ],
              "rows": [
                [
                  "yo",
                  "me"
                ],
                [
                  "tú",
                  "te"
                ],
                [
                  "él/ella/usted",
                  "le"
                ],
                [
                  "nosotros/as",
                  "nos"
                ],
                [
                  "vosotros/as",
                  "os"
                ],
                [
                  "ellos/ellas/ustedes",
                  "les"
                ]
              ]
            }
          ]
        },
        {
          "id": "4.2",
          "title": "Verwendung und Wortstellung",
          "blocks": [
            {
              "type": "text",
              "content": "Indirekte Objektpronomen folgen denselben Regeln für die Wortstellung wie direkte Objektpronomen."
            },
            {
              "type": "rules",
              "items": [
                "Ein verdeutlichender Zusatz mit „a“ wird oft hinzugefügt: „Le doy el libro a María.“",
                "Redundanz ist normal und in vielen Fällen erforderlich: „A mí me gusta.“ / „A ella le duele.“",
                "Indirekte Objekte sind sehr häufig bei Verben wie dar, decir, preguntar, enviar, escribir, comprar, regalar, enseñar, explicar, pedir, contar"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Le escribo una carta a mi abuela.",
                  "en": "Ich schreibe meiner Großmutter einen Brief."
                },
                {
                  "es": "¿Me puedes dar un vaso de agua?",
                  "en": "Kannst du mir ein Glas Wasser geben?"
                },
                {
                  "es": "Les expliqué el problema.",
                  "en": "Ich habe ihnen das Problem erklärt."
                },
                {
                  "es": "Te compré un regalo.",
                  "en": "Ich habe dir ein Geschenk gekauft."
                },
                {
                  "es": "Nos enseñó la ciudad.",
                  "en": "Er hat uns die Stadt gezeigt."
                }
              ]
            }
          ]
        },
        {
          "id": "4.3",
          "title": "Kombination von direkten und indirekten Pronomen (Einführung)",
          "blocks": [
            {
              "type": "text",
              "content": "Wenn beide zusammen auftreten, steht das indirekte Objektpronomen an erster Stelle."
            },
            {
              "type": "rules",
              "items": [
                "me/te/nos/os + lo/la/los/las: „Me lo dio.“ (Er hat es mir gegeben.)",
                "Wenn auf le/les lo/la/los/las folgt, ändert sich le/les zu „se“: „Le di el libro.“ → „Se lo di.“ (Ich habe es ihm/ihr gegeben.)"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¿Me prestas tu bolígrafo? — Te lo presto.",
                  "en": "Leihst du mir deinen Stift? — Ich leihe ihn dir."
                },
                {
                  "es": "Le di las flores a Ana. → Se las di.",
                  "en": "Ich habe Ana die Blumen gegeben. → Ich habe sie ihr gegeben."
                },
                {
                  "es": "¿Nos traes el café? — Os lo traigo ahora.",
                  "en": "Bringst du uns den Kaffee? — Ich bringe ihn euch jetzt."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 4,
      "title": "Der Imperativo (Befehlsform)",
      "sections": [
        {
          "id": "5.1",
          "title": "Bejahender Imperativo (tú) — regelmäßig",
          "blocks": [
            {
              "type": "text",
              "content": "Bejahende tú-Befehlsformen verwenden die él/ella-Form des Presente (Präsens Indikativ)."
            },
            {
              "type": "table",
              "headers": [
                "Infinitiv",
                "tú-Befehlsform",
                "Bedeutung"
              ],
              "rows": [
                [
                  "hablar",
                  "habla",
                  "sprechen"
                ],
                [
                  "comer",
                  "come",
                  "essen"
                ],
                [
                  "escribir",
                  "escribe",
                  "schreiben"
                ],
                [
                  "abrir",
                  "abre",
                  "öffnen"
                ],
                [
                  "leer",
                  "lee",
                  "lesen"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Habla más despacio, por favor.",
                  "en": "Sprich bitte langsamer."
                },
                {
                  "es": "Come tu verdura.",
                  "en": "Iss dein Gemüse."
                },
                {
                  "es": "Abre la ventana.",
                  "en": "Öffne das Fenster."
                }
              ]
            }
          ]
        },
        {
          "id": "5.2",
          "title": "Bejahender Imperativo (tú) — unregelmäßig",
          "blocks": [
            {
              "type": "text",
              "content": "Acht häufige Verben haben unregelmäßige bejahende tú-Befehlsformen."
            },
            {
              "type": "table",
              "headers": [
                "Infinitiv",
                "Befehlsform"
              ],
              "rows": [
                [
                  "decir",
                  "di"
                ],
                [
                  "hacer",
                  "haz"
                ],
                [
                  "ir",
                  "ve"
                ],
                [
                  "poner",
                  "pon"
                ],
                [
                  "salir",
                  "sal"
                ],
                [
                  "ser",
                  "sé"
                ],
                [
                  "tener",
                  "ten"
                ],
                [
                  "venir",
                  "ven"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Haz la tarea.",
                  "en": "Mach die Hausaufgaben."
                },
                {
                  "es": "Ven aquí.",
                  "en": "Komm hierher."
                },
                {
                  "es": "Sal de la habitación.",
                  "en": "Verlass das Zimmer."
                },
                {
                  "es": "Pon la mesa.",
                  "en": "Deck den Tisch."
                },
                {
                  "es": "Di la verdad.",
                  "en": "Sag die Wahrheit."
                }
              ]
            }
          ]
        },
        {
          "id": "5.3",
          "title": "Verneinter Imperativo (tú)",
          "blocks": [
            {
              "type": "text",
              "content": "Verneinte tú-Befehlsformen verwenden die tú-Form des Subjuntivo (spanischer Konjunktiv)."
            },
            {
              "type": "text",
              "content": "Bildung: No + Subjuntivo Presente (tú-Form)"
            },
            {
              "type": "table",
              "headers": [
                "Infinitiv",
                "Verneinte Befehlsform"
              ],
              "rows": [
                [
                  "hablar",
                  "no hables"
                ],
                [
                  "comer",
                  "no comas"
                ],
                [
                  "escribir",
                  "no escribas"
                ],
                [
                  "ir",
                  "no vayas"
                ],
                [
                  "hacer",
                  "no hagas"
                ],
                [
                  "decir",
                  "no digas"
                ],
                [
                  "ser",
                  "no seas"
                ],
                [
                  "tener",
                  "no tengas"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "No hables con la boca llena.",
                  "en": "Sprich nicht mit vollem Mund."
                },
                {
                  "es": "No comas tan rápido.",
                  "en": "Iss nicht so schnell."
                },
                {
                  "es": "No vayas solo.",
                  "en": "Geh nicht alleine."
                },
                {
                  "es": "No seas malo.",
                  "en": "Sei nicht böse."
                }
              ]
            }
          ]
        },
        {
          "id": "5.4",
          "title": "Imperativo für usted / ustedes",
          "blocks": [
            {
              "type": "text",
              "content": "Höfliche Befehlsformen (usted/ustedes) verwenden immer den Subjuntivo, bejaht wie verneint."
            },
            {
              "type": "table",
              "headers": [
                "Infinitiv",
                "Usted",
                "Ustedes"
              ],
              "rows": [
                [
                  "hablar",
                  "hable / no hable",
                  "hablen / no hablen"
                ],
                [
                  "comer",
                  "coma / no coma",
                  "coman / no coman"
                ],
                [
                  "escribir",
                  "escriba / no escriba",
                  "escriban / no escriban"
                ],
                [
                  "ir",
                  "vaya / no vaya",
                  "vayan / no vayan"
                ],
                [
                  "tener",
                  "tenga / no tenga",
                  "tengan / no tengan"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Pase, por favor.",
                  "en": "Treten Sie bitte ein."
                },
                {
                  "es": "No se preocupe.",
                  "en": "Machen Sie sich keine Sorgen."
                },
                {
                  "es": "Siéntense, por favor.",
                  "en": "Setzen Sie sich bitte."
                }
              ]
            }
          ]
        },
        {
          "id": "5.5",
          "title": "Pronomen bei Befehlsformen",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "Bejahende Befehlsformen: Pronomen werden hinten angehängt — „Dime.“ (Sag mir.) / „Cómelo.“ (Iss es.)",
                "Verneinte Befehlsformen: Pronomen stehen vor dem Verb — „No me digas.“ (Sag mir nicht.) / „No lo comas.“ (Iss es nicht.)",
                "Beim Anhängen von Pronomen wird meist ein Akzent (tilde) nötig, damit die ursprüngliche Betonung erhalten bleibt: „Diga“ → „Dígame“ / „Come“ → „Cómelo“. Bei einsilbigen Imperativen (di, haz, pon …) mit nur einem Pronomen entfällt er: „Dime“, „Hazlo“"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Dáselo a tu hermano.",
                  "en": "Gib es deinem Bruder."
                },
                {
                  "es": "No se lo digas a nadie.",
                  "en": "Sag es niemandem."
                },
                {
                  "es": "Escríbeme cuando llegues.",
                  "en": "Schreib mir, wenn du ankommst."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 5,
      "title": "Komparativ und Superlativ",
      "sections": [
        {
          "id": "6.1",
          "title": "Vergleiche der Ungleichheit",
          "blocks": [
            {
              "type": "text",
              "content": "más + Adjektiv/Substantiv/Adverb + que = mehr ... als\nmenos + Adjektiv/Substantiv/Adverb + que = weniger ... als"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Madrid es más grande que Sevilla.",
                  "en": "Madrid ist größer als Sevilla."
                },
                {
                  "es": "Este libro es menos interesante que el otro.",
                  "en": "Dieses Buch ist weniger interessant als das andere."
                },
                {
                  "es": "Tengo más amigos que tú.",
                  "en": "Ich habe mehr Freunde als du."
                },
                {
                  "es": "Habla más rápido que yo.",
                  "en": "Er spricht schneller als ich."
                }
              ]
            }
          ]
        },
        {
          "id": "6.2",
          "title": "Vergleiche der Gleichheit",
          "blocks": [
            {
              "type": "text",
              "content": "tan + Adjektiv/Adverb + como = so ... wie\ntanto/a/os/as + Substantiv + como = so viel/e ... wie\nVerb + tanto como = so viel wie"
            },
            {
              "type": "rules",
              "items": [
                "„Tan“ verändert seine Form nicht",
                "„Tanto“ stimmt mit dem Substantiv überein: tanto dinero, tanta comida, tantos libros, tantas casas"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Soy tan alto como mi padre.",
                  "en": "Ich bin so groß wie mein Vater."
                },
                {
                  "es": "No tengo tantos libros como tú.",
                  "en": "Ich habe nicht so viele Bücher wie du."
                },
                {
                  "es": "Ella trabaja tanto como yo.",
                  "en": "Sie arbeitet so viel wie ich."
                }
              ]
            }
          ]
        },
        {
          "id": "6.3",
          "title": "Unregelmäßige Komparative",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Adjektiv",
                "Komparativ"
              ],
              "rows": [
                [
                  "bueno (gut)",
                  "mejor (besser)"
                ],
                [
                  "malo (schlecht)",
                  "peor (schlechter)"
                ],
                [
                  "grande (groß)",
                  "mayor (älter)"
                ],
                [
                  "pequeño (klein)",
                  "menor (jünger)"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "Sage niemals „más bueno“ für „besser“ — verwende „mejor“",
                "Sage niemals „más malo“ für „schlechter“ — verwende „peor“",
                "„Más grande“ / „más pequeño“ beziehen sich auf die physische Größe; „mayor“ / „menor“ beziehen sich auf das Alter"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Mi hermano es mayor que yo.",
                  "en": "Mein Bruder ist älter als ich."
                },
                {
                  "es": "Esta película es mejor que la otra.",
                  "en": "Dieser Film ist besser als der andere."
                },
                {
                  "es": "Hoy me siento peor que ayer.",
                  "en": "Heute fühle ich mich schlechter als gestern."
                }
              ]
            }
          ]
        },
        {
          "id": "6.4",
          "title": "Superlative",
          "blocks": [
            {
              "type": "text",
              "content": "Relativer Superlativ: el/la/los/las + más/menos + Adjektiv + de\n\nAbsoluter Superlativ: Adjektiv + -ísimo/a/os/as"
            },
            {
              "type": "rules",
              "items": [
                "„De“ wird anstelle von „en“ verwendet (anders als das deutsche „in“): „Es el más alto de la clase.“ (Er ist der Größte in der Klasse.)",
                "Entferne den Endvokal vor -ísimo: grande → grandísimo, bueno → buenísimo"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Es la ciudad más bonita de España.",
                  "en": "Es ist die schönste Stadt in Spanien."
                },
                {
                  "es": "Es el restaurante más caro del barrio.",
                  "en": "Es ist das teuerste Restaurant im Viertel."
                },
                {
                  "es": "La comida estaba riquísima.",
                  "en": "Das Essen war extrem lecker."
                },
                {
                  "es": "Estoy cansadísimo.",
                  "en": "Ich bin extrem müde."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 6,
      "title": "Das Pretérito Perfecto (Perfekt)",
      "sections": [
        {
          "id": "7.1",
          "title": "Bildung",
          "blocks": [
            {
              "type": "text",
              "content": "Das Pretérito Perfecto wird mit dem Presente (Präsens) von „haber“ + dem Participio (Partizip) gebildet."
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Form"
              ],
              "rows": [
                [
                  "yo",
                  "he"
                ],
                [
                  "tú",
                  "has"
                ],
                [
                  "él/ella/usted",
                  "ha"
                ],
                [
                  "nosotros/as",
                  "hemos"
                ],
                [
                  "vosotros/as",
                  "habéis"
                ],
                [
                  "ellos/ellas/ustedes",
                  "han"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "-ar → -ado: hablar → hablado, comprar → comprado",
                "-er → -ido: comer → comido, beber → bebido",
                "-ir → -ido: vivir → vivido, salir → salido"
              ]
            }
          ]
        },
        {
          "id": "7.2",
          "title": "Unregelmäßige Participios",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Infinitiv",
                "Participio"
              ],
              "rows": [
                [
                  "abrir",
                  "abierto"
                ],
                [
                  "decir",
                  "dicho"
                ],
                [
                  "escribir",
                  "escrito"
                ],
                [
                  "hacer",
                  "hecho"
                ],
                [
                  "morir",
                  "muerto"
                ],
                [
                  "poner",
                  "puesto"
                ],
                [
                  "resolver",
                  "resuelto"
                ],
                [
                  "romper",
                  "roto"
                ],
                [
                  "ver",
                  "visto"
                ],
                [
                  "volver",
                  "vuelto"
                ]
              ]
            }
          ]
        },
        {
          "id": "7.3",
          "title": "Verwendung",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "Handlungen, die in einem Zeitraum abgeschlossen wurden, der mit der Gegenwart verbunden ist: hoy (heute), esta semana (diese Woche), este año (dieses Jahr)",
                "Lebenserfahrungen: „¿Has estado en México?“ (Warst du schon in Mexiko?)",
                "Kürzliche Vergangenheit mit „ya“ (bereits) und „todavía no“ (noch nicht)",
                "Das Participio ändert sich in zusammengesetzten Zeiten nie nach Genus oder Numerus."
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Hoy he trabajado mucho.",
                  "en": "Heute habe ich viel gearbeitet."
                },
                {
                  "es": "¿Has comido ya?",
                  "en": "Hast du schon gegessen?"
                },
                {
                  "es": "Todavía no he terminado.",
                  "en": "Ich bin noch nicht fertig."
                },
                {
                  "es": "Este año hemos viajado a Italia.",
                  "en": "Dieses Jahr sind wir nach Italien gereist."
                },
                {
                  "es": "Nunca he visto esa película.",
                  "en": "Ich habe diesen Film noch nie gesehen."
                },
                {
                  "es": "¿Alguna vez has probado la paella?",
                  "en": "Hast du schon einmal Paella probiert?"
                }
              ]
            }
          ]
        },
        {
          "id": "7.4",
          "title": "Pretérito Perfecto vs. Indefinido (einfache Vergangenheit)",
          "blocks": [
            {
              "type": "text",
              "content": "In Spanien wird das Pretérito Perfecto für kürzliche Ereignisse oder Ereignisse am selben Tag verwendet; das Indefinido wird für abgeschlossene vergangene Ereignisse verwendet. In Lateinamerika ist das Indefinido für beides gebräuchlicher."
            },
            {
              "type": "table",
              "headers": [
                "Spanien (Pretérito Perfecto)",
                "Lateinamerika (Indefinido)"
              ],
              "rows": [
                [
                  "Hoy he comido paella.",
                  "Hoy comí paella."
                ],
                [
                  "Esta mañana he ido al médico.",
                  "Esta mañana fui al médico."
                ]
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 7,
      "title": "Präpositionen — Erweiterung",
      "sections": [
        {
          "id": "8.1",
          "title": "Por vs. Para — Kernunterschied",
          "blocks": [
            {
              "type": "text",
              "content": "Por — verwende es für:"
            },
            {
              "type": "rules",
              "items": [
                "Grund / Ursache: „Gracias por tu ayuda.“ (Danke für deine Hilfe.)",
                "Dauer: „Estudié por dos horas.“ (Ich habe zwei Stunden lang gelernt.)",
                "Austausch: „Lo compré por diez euros.“ (Ich habe es für zehn Euro gekauft.)",
                "Bewegung durch: „Caminé por el parque.“ (Ich bin durch den Park spaziert.)",
                "Tageszeit (allgemein): „Por la mañana estudio.“ (Am Morgen lerne ich.)",
                "Pro: „Tres veces por semana.“ (Dreimal pro Woche.)"
              ]
            },
            {
              "type": "text",
              "content": "Para — verwende es für:"
            },
            {
              "type": "rules",
              "items": [
                "Zweck / Ziel: „Estudio para aprender.“ (Ich studiere, um zu lernen.)",
                "Empfänger: „Este regalo es para ti.“ (Dieses Geschenk ist für dich.)",
                "Zielort: „Salgo para México.“ (Ich reise nach Mexiko ab.)",
                "Frist / Deadline: „Es para el viernes.“ (Es ist für Freitag / bis Freitag fällig.)",
                "Meinung: „Para mí, es fácil.“ (Für mich ist es einfach.)",
                "Vergleich: „Para un niño, cocina muy bien.“ (Für ein Kind kocht er sehr gut.)"
              ]
            }
          ]
        },
        {
          "id": "8.2",
          "title": "Häufige Präpositionalausdrücke",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Ausdruck",
                "Bedeutung"
              ],
              "rows": [
                [
                  "al lado de",
                  "neben"
                ],
                [
                  "delante de",
                  "vor (räumlich)"
                ],
                [
                  "detrás de",
                  "hinter"
                ],
                [
                  "encima de",
                  "auf / oben auf"
                ],
                [
                  "debajo de",
                  "unter"
                ],
                [
                  "dentro de",
                  "innerhalb / in"
                ],
                [
                  "fuera de",
                  "außerhalb"
                ],
                [
                  "cerca de",
                  "in der Nähe von"
                ],
                [
                  "lejos de",
                  "weit weg von"
                ],
                [
                  "enfrente de",
                  "gegenüber von"
                ],
                [
                  "a la derecha de",
                  "rechts von"
                ],
                [
                  "a la izquierda de",
                  "links von"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "El banco está al lado del supermercado.",
                  "en": "Die Bank ist neben dem Supermarkt."
                },
                {
                  "es": "Mi casa está cerca de la estación.",
                  "en": "Mein Haus ist in der Nähe des Bahnhofs."
                },
                {
                  "es": "El gato está debajo de la mesa.",
                  "en": "Die Katze ist unter dem Tisch."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 8,
      "title": "Konnektoren und Satzstruktur",
      "sections": [
        {
          "id": "9.1",
          "title": "Ursache und Grund",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Konnektor",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "porque",
                  "weil",
                  "No fui porque estaba enfermo."
                ],
                [
                  "como (Satzanfang)",
                  "da / weil",
                  "Como llovía, me quedé en casa."
                ],
                [
                  "ya que",
                  "da / zumal",
                  "Ya que estás aquí, ayúdame."
                ],
                [
                  "por eso",
                  "deshalb",
                  "Estaba cansado, por eso no salí."
                ]
              ]
            }
          ]
        },
        {
          "id": "9.2",
          "title": "Gegensatz",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Konnektor",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "pero",
                  "aber",
                  "Es caro, pero muy bueno."
                ],
                [
                  "aunque",
                  "obwohl",
                  "Aunque llueve, voy a salir."
                ],
                [
                  "sin embargo",
                  "jedoch",
                  "Es difícil. Sin embargo, lo intentaré."
                ]
              ]
            }
          ]
        },
        {
          "id": "9.3",
          "title": "Folge",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Konnektor",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "por eso",
                  "deshalb",
                  "No estudié, por eso suspendí."
                ],
                [
                  "así que",
                  "also / deshalb",
                  "No había taxis, así que caminé."
                ],
                [
                  "entonces",
                  "dann / also",
                  "No tenía hambre, entonces no comí."
                ]
              ]
            }
          ]
        },
        {
          "id": "9.4",
          "title": "Reihenfolge",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Konnektor",
                "Bedeutung"
              ],
              "rows": [
                [
                  "primero",
                  "zuerst"
                ],
                [
                  "luego / después",
                  "dann / danach"
                ],
                [
                  "más tarde",
                  "später"
                ],
                [
                  "por último / finalmente",
                  "schließlich"
                ],
                [
                  "al final",
                  "am Ende"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Primero desayuné, luego fui al trabajo y finalmente cené con amigos.",
                  "en": "Zuerst habe ich gefrühstückt, dann bin ich zur Arbeit gegangen und schließlich habe ich mit Freunden zu Abend gegessen."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 9,
      "title": "Die nahe Zukunft und andere Verbstrukturen",
      "sections": [
        {
          "id": "10.1",
          "title": "Ir a + Infinitiv (Wiederholung)",
          "blocks": [
            {
              "type": "text",
              "content": "Wird für Pläne, Absichten und Handlungen in der nahen Zukunft verwendet."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Voy a estudiar esta noche.",
                  "en": "Ich werde heute Abend lernen."
                },
                {
                  "es": "¿Qué vas a hacer mañana?",
                  "en": "Was wirst du morgen tun?"
                },
                {
                  "es": "Vamos a viajar a México.",
                  "en": "Wir werden nach Mexiko reisen."
                }
              ]
            }
          ]
        },
        {
          "id": "10.2",
          "title": "Acabar de + Infinitiv (gerade getan)",
          "blocks": [
            {
              "type": "text",
              "content": "Drückt eine Handlung aus, die gerade eben geschehen ist."
            },
            {
              "type": "text",
              "content": "Struktur: acabar im Presente (Präsens) + de + Infinitiv"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Acabo de llegar.",
                  "en": "Ich bin gerade angekommen."
                },
                {
                  "es": "Acabamos de comer.",
                  "en": "Wir haben gerade gegessen."
                },
                {
                  "es": "Acaba de llamar tu madre.",
                  "en": "Deine Mutter hat gerade angerufen."
                }
              ]
            }
          ]
        },
        {
          "id": "10.3",
          "title": "Estar + Gerundio (Verlaufsform auf -ando/-iendo) — Wiederholung",
          "blocks": [
            {
              "type": "text",
              "content": "Für Handlungen, die genau jetzt stattfinden."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Estoy estudiando.",
                  "en": "Ich lerne gerade."
                },
                {
                  "es": "¿Qué estás haciendo?",
                  "en": "Was machst du gerade?"
                },
                {
                  "es": "Están jugando en el parque.",
                  "en": "Sie spielen gerade im Park."
                }
              ]
            }
          ]
        },
        {
          "id": "10.4",
          "title": "Soler + Infinitiv (gewöhnlich tun)",
          "blocks": [
            {
              "type": "text",
              "content": "Drückt gewohnheitsmäßige Handlungen aus."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Suelo desayunar a las ocho.",
                  "en": "Normalerweise frühstücke ich um acht Uhr."
                },
                {
                  "es": "¿Qué sueles hacer los fines de semana?",
                  "en": "Was machst du normalerweise am Wochenende?"
                },
                {
                  "es": "Solíamos ir al campo de niños.",
                  "en": "Als Kinder fuhren wir gewöhnlich aufs Land. (soler im Imperfecto, der Verlaufsvergangenheit)"
                }
              ]
            }
          ]
        },
        {
          "id": "10.5",
          "title": "Volver a + Infinitiv (wieder tun)",
          "blocks": [
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Volvió a llamar.",
                  "en": "Er hat wieder angerufen."
                },
                {
                  "es": "No vuelvas a llegar tarde.",
                  "en": "Komm nicht wieder zu spät."
                },
                {
                  "es": "Volví a leer el libro.",
                  "en": "Ich habe das Buch wieder gelesen."
                }
              ]
            }
          ]
        },
        {
          "id": "10.6",
          "title": "Empezar a / Terminar de + Infinitiv",
          "blocks": [
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Empecé a estudiar a las tres.",
                  "en": "Ich habe um drei Uhr angefangen zu lernen."
                },
                {
                  "es": "Terminé de leer el libro.",
                  "en": "Ich habe das Buch zu Ende gelesen."
                },
                {
                  "es": "Cuando empezó a llover, entramos en casa.",
                  "en": "Als es anfing zu regnen, gingen wir ins Haus."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 10,
      "title": "Reflexive Verben — Erweiterung",
      "sections": [
        {
          "id": "11.1",
          "title": "Wiederholung der reflexiven Verben für den Tagesablauf",
          "blocks": [
            {
              "type": "text",
              "content": "levantarse (aufstehen), acostarse (ins Bett gehen), ducharse (duschen), lavarse (sich waschen), vestirse (sich anziehen), peinarse (sich kämmen), despertarse (aufwachen)"
            }
          ]
        },
        {
          "id": "11.2",
          "title": "Reflexive Verben für Gefühle und Zustände",
          "blocks": [
            {
              "type": "text",
              "content": "Viele Verben, die Gefühle, Zustände oder Veränderungen ausdrücken, verwenden reflexive Pronomen."
            },
            {
              "type": "table",
              "headers": [
                "Verb",
                "Bedeutung"
              ],
              "rows": [
                [
                  "sentirse",
                  "sich fühlen"
                ],
                [
                  "divertirse",
                  "Spaß haben"
                ],
                [
                  "aburrirse",
                  "sich langweilen"
                ],
                [
                  "enfadarse / enojarse",
                  "sich ärgern"
                ],
                [
                  "preocuparse",
                  "sich Sorgen machen"
                ],
                [
                  "alegrarse",
                  "sich freuen"
                ],
                [
                  "asustarse",
                  "sich erschrecken"
                ],
                [
                  "enamorarse",
                  "sich verlieben"
                ],
                [
                  "cansarse",
                  "müde werden"
                ],
                [
                  "equivocarse",
                  "sich irren"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Me siento muy bien hoy.",
                  "en": "Ich fühle mich heute sehr gut."
                },
                {
                  "es": "Nos divertimos mucho en la fiesta.",
                  "en": "Wir hatten viel Spaß auf der Party."
                },
                {
                  "es": "Se enfadó con su hermano.",
                  "en": "Er ärgerte sich über seinen Bruder."
                },
                {
                  "es": "Me preocupo por mi familia.",
                  "en": "Ich mache mir Sorgen um meine Familie."
                },
                {
                  "es": "Se enamoró de ella en la universidad.",
                  "en": "Er verliebte sich an der Universität in sie."
                }
              ]
            }
          ]
        },
        {
          "id": "11.3",
          "title": "Reflexive Pronomen im Indefinido und Imperfecto",
          "blocks": [
            {
              "type": "text",
              "content": "Reflexive Pronomen folgen in den Vergangenheitsformen denselben Stellungsregeln."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Me levanté a las siete.",
                  "en": "Ich bin um sieben Uhr aufgestanden. (Indefinido)"
                },
                {
                  "es": "Se duchaba todos los días.",
                  "en": "Er duschte jeden Tag. (Imperfecto)"
                },
                {
                  "es": "Nos divertimos mucho el sábado.",
                  "en": "Wir hatten am Samstag viel Spaß. (Indefinido)"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 11,
      "title": "Personen, Orte und Erlebnisse beschreiben",
      "sections": [
        {
          "id": "12.1",
          "title": "Körperliche Beschreibungen",
          "blocks": [
            {
              "type": "text",
              "content": "Häufige Adjektive: alto/a (groß), bajo/a (klein), delgado/a (schlank), gordo/a (dick), guapo/a (gutaussehend/hübsch), joven (jung), viejo/a (alt), rubio/a (blond), moreno/a (dunkelhaarig), calvo/a (glatzköpfig)"
            },
            {
              "type": "rules",
              "items": [
                "Ser für körperliche Merkmale: „Es alto y moreno.“ (Er ist groß und dunkelhaarig.)",
                "Tener für einzelne Merkmale: „Tiene los ojos azules.“ (Er hat blaue Augen.) / „Tiene el pelo largo.“ (Sie hat lange Haare.)"
              ]
            }
          ]
        },
        {
          "id": "12.2",
          "title": "Charakter und Persönlichkeit",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Adjektiv",
                "Bedeutung",
                "Gegenteil"
              ],
              "rows": [
                [
                  "simpático/a",
                  "nett, freundlich",
                  "antipático/a (unsympathisch)"
                ],
                [
                  "amable",
                  "freundlich, liebenswürdig",
                  "maleducado/a (unhöflich)"
                ],
                [
                  "generoso/a",
                  "großzügig",
                  "tacaño/a (geizig)"
                ],
                [
                  "trabajador/a",
                  "fleißig",
                  "perezoso/a / vago/a (faul)"
                ],
                [
                  "inteligente",
                  "intelligent",
                  "tonto/a (dumm, albern)"
                ],
                [
                  "divertido/a",
                  "lustig, unterhaltsam",
                  "aburrido/a (langweilig)"
                ],
                [
                  "tímido/a",
                  "schüchtern",
                  "extrovertido/a (kontaktfreudig)"
                ],
                [
                  "tranquilo/a",
                  "ruhig",
                  "nervioso/a (nervös)"
                ],
                [
                  "responsable",
                  "verantwortungsbewusst",
                  "irresponsable (verantwortungslos)"
                ],
                [
                  "honesto/a",
                  "ehrlich",
                  "mentiroso/a (unehrlich, verlogen)"
                ]
              ]
            }
          ]
        },
        {
          "id": "12.3",
          "title": "Orte beschreiben",
          "blocks": [
            {
              "type": "text",
              "content": "Nützlicher Wortschatz: grande/pequeño (groß/klein), bonito/feo (schön/hässlich), moderno/antiguo (modern/alt), ruidoso/tranquilo (laut/ruhig), limpio/sucio (sauber/schmutzig), seguro/peligroso (sicher/gefährlich)"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Mi barrio es muy tranquilo y tiene muchos parques.",
                  "en": "Mein Viertel ist sehr ruhig und hat viele Parks."
                },
                {
                  "es": "La ciudad es grande y moderna, pero un poco ruidosa.",
                  "en": "Die Stadt ist groß und modern, aber ein bisschen laut."
                }
              ]
            }
          ]
        },
        {
          "id": "12.4",
          "title": "Erlebnisse beschreiben",
          "blocks": [
            {
              "type": "text",
              "content": "Nützliche Verben und Strukturen:\n- fue + Adjektiv: „Fue increíble.“ (Es war unglaublich.)\n- Lo mejor fue... : „Lo mejor fue la comida.“ (Das Beste war das Essen.)\n- Lo peor fue... : „Lo peor fue el tráfico.“ (Das Schlimmste war der Verkehr.)\n- Lo pasé muy bien / mal: „Lo pasé genial.“ (Ich hatte richtig Spaß.)"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "El viaje fue maravilloso. Lo mejor fue visitar las playas. Lo pasé muy bien.",
                  "en": "Die Reise war wunderbar. Das Beste war der Besuch der Strände. Ich hatte viel Spaß."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 12,
      "title": "Wetter und Natur",
      "sections": [
        {
          "id": "13.1",
          "title": "Wetterausdrücke",
          "blocks": [
            {
              "type": "text",
              "content": "Die meisten Wetterausdrücke verwenden „hacer“ (3. Person Singular)."
            },
            {
              "type": "table",
              "headers": [
                "Ausdruck",
                "Bedeutung"
              ],
              "rows": [
                [
                  "Hace calor.",
                  "Es ist heiß."
                ],
                [
                  "Hace frío.",
                  "Es ist kalt."
                ],
                [
                  "Hace sol.",
                  "Es ist sonnig."
                ],
                [
                  "Hace viento.",
                  "Es ist windig."
                ],
                [
                  "Hace buen/mal tiempo.",
                  "Das Wetter ist gut/schlecht."
                ],
                [
                  "Llueve. / Está lloviendo.",
                  "Es regnet."
                ],
                [
                  "Nieva. / Está nevando.",
                  "Es schneit."
                ],
                [
                  "Hay niebla.",
                  "Es ist neblig."
                ],
                [
                  "Hay tormenta.",
                  "Es gibt ein Gewitter."
                ],
                [
                  "Está nublado.",
                  "Es ist bewölkt."
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Ayer hizo mucho calor.",
                  "en": "Gestern war es sehr heiß."
                },
                {
                  "es": "Cuando era niño, nevaba mucho.",
                  "en": "Als ich ein Kind war, schneite es viel."
                },
                {
                  "es": "Hacía sol cuando salimos.",
                  "en": "Es war sonnig, als wir hinausgingen."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 13,
      "title": "Zahlen, Mengen und Ausdrücke",
      "sections": [
        {
          "id": "14.1",
          "title": "Zahlen 100–1.000.000",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Zahl",
                "Spanisch"
              ],
              "rows": [
                [
                  "100",
                  "cien / ciento"
                ],
                [
                  "200",
                  "doscientos/as"
                ],
                [
                  "300",
                  "trescientos/as"
                ],
                [
                  "400",
                  "cuatrocientos/as"
                ],
                [
                  "500",
                  "quinientos/as"
                ],
                [
                  "600",
                  "seiscientos/as"
                ],
                [
                  "700",
                  "setecientos/as"
                ],
                [
                  "800",
                  "ochocientos/as"
                ],
                [
                  "900",
                  "novecientos/as"
                ],
                [
                  "1.000",
                  "mil"
                ],
                [
                  "2.000",
                  "dos mil"
                ],
                [
                  "1.000.000",
                  "un millón"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "„Cien“ wird allein oder vor Substantiven verwendet: „cien personas“ (100 Personen)",
                "„Ciento“ wird verwendet, wenn weitere Zahlen folgen: „ciento cincuenta“ (150)",
                "Hunderter stimmen im Genus mit dem Substantiv überein: „doscientas personas“ (200 Personen, fem.)",
                "„Mil“ verändert sich nicht: „dos mil“, „tres mil“",
                "„Millón“ erfordert „de“ vor Substantiven: „un millón de euros“"
              ]
            }
          ]
        },
        {
          "id": "14.2",
          "title": "Mengen ausdrücken",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Ausdruck",
                "Bedeutung"
              ],
              "rows": [
                [
                  "un poco de",
                  "ein wenig / etwas"
                ],
                [
                  "mucho/a",
                  "viel"
                ],
                [
                  "poco/a",
                  "wenig / nicht viel"
                ],
                [
                  "bastante",
                  "ziemlich viel"
                ],
                [
                  "demasiado/a",
                  "zu viel"
                ],
                [
                  "suficiente",
                  "genug"
                ],
                [
                  "varios/as",
                  "mehrere"
                ],
                [
                  "algunos/as",
                  "einige"
                ],
                [
                  "ningún / ninguna",
                  "kein / keine"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Quiero un poco de agua.",
                  "en": "Ich möchte ein wenig Wasser."
                },
                {
                  "es": "Hay demasiada gente.",
                  "en": "Es sind zu viele Leute da."
                },
                {
                  "es": "¿Tienes suficiente dinero?",
                  "en": "Hast du genug Geld?"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
