import { GrammarLevel } from './types'

// GENERATED by scripts/translate-grammar.ts — reviewed and corrected by hand.
// German explanations, Spanish examples untouched. Example `en` fields hold the
// German gloss (the Block renderer shows that field as the secondary line).
// Re-running the script will NOT clobber this file's cache; delete
// scripts/.cache/grammar-de/c1-*.json to force a re-translation.
export const grammarC1De: GrammarLevel = {
  "level": "C1",
  "title": "Spanische Grammatik für Fortgeschrittene",
  "chapters": [
    {
      "id": 0,
      "title": "Erweiterte Verwendung des Subjuntivo",
      "sections": [
        {
          "id": "1.1",
          "title": "Der Subjuntivo in Hauptsätzen",
          "blocks": [
            {
              "type": "text",
              "content": "Auf Niveau C1 ist der Subjuntivo nicht auf Nebensätze beschränkt. Er erscheint auch in Hauptsätzen, um Wünsche, Zweifel oder emotionale Reaktionen auszudrücken."
            },
            {
              "type": "table",
              "headers": [
                "Ausdruck",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "Ojala + Presente de Subjuntivo",
                  "Ich hoffe (möglich)",
                  "Ojala llueva mañana. -- Ich hoffe, es regnet morgen."
                ],
                [
                  "Ojala + Imperfecto de Subjuntivo",
                  "Ich wünschte (unwahrscheinliche Gegenwart)",
                  "Ojala tuviera mas tiempo. -- Ich wünschte, ich hätte mehr Zeit."
                ],
                [
                  "Ojala + Pluscuamperfecto de Subjuntivo",
                  "Ich wünschte (unmögliche Vergangenheit)",
                  "Ojala hubiera estudiado mas. -- Ich wünschte, ich hätte mehr gelernt."
                ],
                [
                  "Que + Presente de Subjuntivo",
                  "Möge... / Auf dass...",
                  "Que te vaya bien! -- Möge es dir gut gehen!"
                ],
                [
                  "Quien + Imperfecto de Subjuntivo",
                  "Wenn ich doch nur könnte...",
                  "Quien pudiera volar! -- Wenn ich doch fliegen könnte!"
                ],
                [
                  "Quien + Pluscuamperfecto de Subjuntivo",
                  "Hätte ich doch...",
                  "Quien lo hubiera sabido! -- Hätte ich das nur gewusst!"
                ],
                [
                  "Así + Presente de Subjuntivo",
                  "Ich hoffe (umgangssprachlicher Fluch)",
                  "Así le vaya mal! -- Ich hoffe, es ergeht ihm schlecht!"
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Ojala no haya mucho trafico.",
                  "en": "Ich hoffe, es gibt nicht viel Verkehr."
                },
                {
                  "es": "Ojala pudiera volver a esos tiempos.",
                  "en": "Ich wünschte, ich könnte in diese Zeiten zurückkehren."
                },
                {
                  "es": "Que tengas un buen día!",
                  "en": "Hab einen schönen Tag!"
                },
                {
                  "es": "Quien pudiera estar en la playa ahora!",
                  "en": "Wenn ich jetzt nur am Strand sein könnte!"
                }
              ]
            }
          ]
        },
        {
          "id": "1.2",
          "title": "Der Subjuntivo nach Wahrscheinlichkeitsausdrücken",
          "blocks": [
            {
              "type": "text",
              "content": "Die Wahl zwischen Indikativ und Subjuntivo bei Wahrscheinlichkeitsausdrücken hängt vom Grad der Gewissheit ab."
            },
            {
              "type": "rules",
              "items": [
                "Indikativ (hohe Gewissheit): Es evidente que... / Es obvio que... / Es cierto que... / Esta claro que...",
                "\"Es evidente que tiene razon.\" -- Es ist offensichtlich, dass er recht hat."
              ]
            },
            {
              "type": "rules",
              "items": [
                "Subjuntivo (Zweifel, geringe Gewissheit): Es posible que... / Es probable que... / Puede que... / Es dudoso que...",
                "\"Es posible que venga mañana.\" -- Es ist möglich, dass er morgen kommt.",
                "\"Puede que llueva esta tarde.\" -- Es könnte heute Nachmittag regnen."
              ]
            },
            {
              "type": "rules",
              "items": [
                "Verneinte Gewissheit löst den Subjuntivo aus",
                "\"No es cierto que sea así.\" -- Es ist nicht wahr, dass es so ist.",
                "\"No esta claro que vayan a ganar.\" -- Es ist nicht klar, dass sie gewinnen werden."
              ]
            }
          ]
        },
        {
          "id": "1.3",
          "title": "Der Subjuntivo in Konzessivsätzen",
          "blocks": [
            {
              "type": "text",
              "content": "Konzessivsätze räumen einen gegensätzlichen Punkt ein, während sie die Hauptidee bekräftigen. Der Modus hängt davon ab, ob die eingeräumte Tatsache real oder hypothetisch ist."
            },
            {
              "type": "rules",
              "items": [
                "Aunque + Indikativ (Tatsache): \"Aunque esta lloviendo, salgo.\" -- Obwohl es regnet, gehe ich raus.",
                "Aunque + Subjuntivo (hypothetisch): \"Aunque este lloviendo, saldre.\" -- Selbst wenn es regnet, werde ich ausgehen."
              ]
            },
            {
              "type": "table",
              "headers": [
                "Ausdruck",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "por mas que",
                  "egal wie sehr",
                  "Por mas que lo intente, no lo consigo."
                ],
                [
                  "por mucho que",
                  "egal wie viel",
                  "Por mucho que estudie, no aprueba."
                ],
                [
                  "por poco que",
                  "egal wie wenig",
                  "Por poco que haga, siempre ayuda."
                ],
                [
                  "por muy + adj. + que",
                  "so ... auch (+ Adjektiv)",
                  "Por muy cansado que este, sigue trabajando."
                ],
                [
                  "aun cuando",
                  "selbst wenn / auch wenn",
                  "Aun cuando lo sepa, no dira nada."
                ],
                [
                  "si bien",
                  "obwohl, auch wenn",
                  "Si bien es difícil, no es imposible."
                ],
                [
                  "a sabiendas de que",
                  "wohl wissend, dass",
                  "Lo hizo a sabiendas de que estaba mal."
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Por mas que le explique el problema, no lo entendio.",
                  "en": "Egal wie sehr ich ihm das Problem erklärte, er verstand es nicht."
                },
                {
                  "es": "Por muy inteligente que sea, comete errores.",
                  "en": "So intelligent er auch sein mag, er macht Fehler."
                }
              ]
            }
          ]
        },
        {
          "id": "1.4",
          "title": "Der Subjuntivo in Temporalsätzen -- Nuancen",
          "blocks": [
            {
              "type": "text",
              "content": "Auf Niveau C1 offenbaren temporale Konjunktionen subtile Verschiebungen zwischen Indikativ und Subjuntivo."
            },
            {
              "type": "table",
              "headers": [
                "Konjunktion",
                "Indikativ (Vergangenheits-/Gegenwartstatsache)",
                "Subjuntivo (Zukunft / hypothetisch)"
              ],
              "rows": [
                [
                  "cuando",
                  "Cuando llegue, llovia.",
                  "Cuando llegues, llamame."
                ],
                [
                  "en cuanto / tan pronto como",
                  "En cuanto lo vi, lo reconoci.",
                  "En cuanto lo vea, se lo dire."
                ],
                [
                  "hasta que",
                  "Espere hasta que llego.",
                  "Espera hasta que llegue."
                ],
                [
                  "después de que",
                  "Después de que termino, se fue.",
                  "Después de que termine, iremos."
                ],
                [
                  "mientras",
                  "Mientras estudiaba, escuchaba música.",
                  "Mientras vivas aquí, respeta las normas."
                ],
                [
                  "antes de que",
                  "(immer Subjuntivo)",
                  "Sal antes de que llueva."
                ],
                [
                  "una vez que",
                  "Una vez que lo supo, actuo.",
                  "Una vez que lo sepas, dime."
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "\"Antes de que\" erfordert IMMER den Subjuntivo, da die Handlung im Nebensatz per Definition noch nicht stattgefunden hat."
              ]
            }
          ]
        },
        {
          "id": "1.5",
          "title": "Der Subjuntivo nach Werturteilen",
          "blocks": [
            {
              "type": "text",
              "content": "Unpersönliche Ausdrücke, die ein Werturteil vermitteln, lösen den Subjuntivo aus."
            },
            {
              "type": "table",
              "headers": [
                "Ausdruck",
                "Beispiel"
              ],
              "rows": [
                [
                  "Es normal que + subj.",
                  "Es normal que estes nervioso."
                ],
                [
                  "Es logico que + subj.",
                  "Es logico que quiera irse."
                ],
                [
                  "Es justo que + subj.",
                  "Es justo que reciban un premio."
                ],
                [
                  "Es ridiculo que + subj.",
                  "Es ridiculo que piense así."
                ],
                [
                  "Es una pena que + subj.",
                  "Es una pena que no puedas venir."
                ],
                [
                  "Es extrano que + subj.",
                  "Es extrano que no haya llamado."
                ],
                [
                  "Es sorprendente que + subj.",
                  "Es sorprendente que haya ganado."
                ],
                [
                  "Esta bien / mal que + subj.",
                  "Esta mal que no diga la verdad."
                ],
                [
                  "Mas vale que + subj.",
                  "Mas vale que te des prisa."
                ]
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 1,
      "title": "Erweiterte Konditionalsätze",
      "sections": [
        {
          "id": "2.1",
          "title": "Wiederholung: Die drei Haupttypen + Gemischt",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Typ",
                "Si-Satz",
                "Hauptsatz",
                "Bedeutung"
              ],
              "rows": [
                [
                  "1 (real)",
                  "Presente de Indicativo",
                  "Futuro / Presente / Imperativo",
                  "möglich"
                ],
                [
                  "2 (hypothetisch)",
                  "Imperfecto de Subjuntivo",
                  "Condicional",
                  "unwahrscheinliche Gegenwart"
                ],
                [
                  "3 (kontrafaktisch)",
                  "Pluscuamperfecto de Subjuntivo",
                  "Condicional Compuesto",
                  "unmögliche Vergangenheit"
                ],
                [
                  "Gemischt A",
                  "Pluscuamperfecto de Subjuntivo",
                  "Condicional",
                  "Vergangenheitsursache -> Gegenwartsergebnis"
                ],
                [
                  "Gemischt B",
                  "Imperfecto de Subjuntivo",
                  "Condicional Compuesto",
                  "Gegenwartsursache -> Vergangenheitsergebnis"
                ]
              ]
            }
          ]
        },
        {
          "id": "2.2",
          "title": "De + Infinitiv als konditionale Alternative",
          "blocks": [
            {
              "type": "text",
              "content": "\"De + Infinitiv\" kann in formellen oder literarischen Registern \"si + konjugiertes Verb\" ersetzen."
            },
            {
              "type": "rules",
              "items": [
                "\"De + Infinitiv\" = si + Presente/Imperfecto de Subjuntivo (hypothetisch)",
                "\"De + haber + participio\" = si + Pluscuamperfecto de Subjuntivo (kontrafaktisch)",
                "Häufiger im geschriebenen Spanisch"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "De tener mas tiempo, estudiaria mas.",
                  "en": "Wenn ich mehr Zeit hätte, würde ich mehr lernen."
                },
                {
                  "es": "De haberlo sabido, no habria venido.",
                  "en": "Hätte ich es gewusst, wäre ich nicht gekommen."
                },
                {
                  "es": "De ser posible, me gustaria cambiar de horario.",
                  "en": "Wäre es möglich, würde ich gerne meinen Stundenplan ändern."
                },
                {
                  "es": "De no llover, iremos a la playa.",
                  "en": "Wenn es nicht regnet, gehen wir an den Strand."
                }
              ]
            }
          ]
        },
        {
          "id": "2.3",
          "title": "Como + Subjuntivo (Konditionale Warnung/Drohung)",
          "blocks": [
            {
              "type": "text",
              "content": "\"Como\" + Presente de Subjuntivo fungiert als konditionale Warnung oder Drohung und entspricht \"wenn (du)...\""
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Como no estudies, suspenderas.",
                  "en": "Wenn du nicht lernst, wirst du durchfallen."
                },
                {
                  "es": "Como vuelvas a llegar tarde, te despiden.",
                  "en": "Wenn du noch einmal zu spät kommst, feuern sie dich."
                },
                {
                  "es": "Como me entere de que mientes, se acabo.",
                  "en": "Wenn ich herausfinde, dass du lügst, ist Schluss."
                }
              ]
            }
          ]
        },
        {
          "id": "2.4",
          "title": "Con + Infinitiv / Con que + Subjuntivo (Vorausgesetzt, dass)",
          "blocks": [
            {
              "type": "text",
              "content": "\"Con + Infinitiv\" und \"con que + Subjuntivo\" drücken eine hinreichende Bedingung aus."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Con estudiar un poco mas, aprobaras.",
                  "en": "Wenn du ein bisschen mehr lernst, wirst du bestehen."
                },
                {
                  "es": "Con que vengas a las ocho, es suficiente.",
                  "en": "Solange du um acht Uhr kommst, reicht das."
                }
              ]
            }
          ]
        },
        {
          "id": "2.5",
          "title": "A no ser que / Excepto que / Salvo que (Es sei denn, dass)",
          "blocks": [
            {
              "type": "text",
              "content": "Alle drei bedeuten \"es sei denn\" und verlangen den Subjuntivo."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Ire a no ser que llueva.",
                  "en": "Ich gehe, es sei denn, es regnet."
                },
                {
                  "es": "Te esperare, salvo que me digas lo contrario.",
                  "en": "Ich werde auf dich warten, es sei denn, du sagst mir etwas anderes."
                },
                {
                  "es": "Llegaremos a tiempo, excepto que haya mucho trafico.",
                  "en": "Wir werden pünktlich ankommen, es sei denn, es gibt viel Verkehr."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 2,
      "title": "Erweiterte Passiv- und unpersönliche Konstruktionen",
      "sections": [
        {
          "id": "3.1",
          "title": "Reflexivpassiv (se) vs. unpersönliches se -- Präzise Unterscheidung",
          "blocks": [
            {
              "type": "text",
              "content": "Auf Niveau C1 musst du präzise zwischen diesen beiden \"se\"-Konstruktionen unterscheiden."
            },
            {
              "type": "rules",
              "items": [
                "Reflexivpassiv (pasiva refleja): Das Objekt, an dem die Handlung vollzogen wird, ist das grammatikalische Subjekt; das Verb richtet sich danach",
                "\"Se venden pisos.\" -- Wohnungen werden verkauft. (pisos = Subjekt, Verb im Plural)",
                "\"Se habla español.\" -- Spanisch wird gesprochen. (español = Subjekt, Verb im Singular)"
              ]
            },
            {
              "type": "rules",
              "items": [
                "Unpersönliches se: Kein grammatikalisches Subjekt; das Verb steht immer in der 3. Person Singular",
                "\"Se trabaja mucho aquí.\" -- Hier wird viel gearbeitet.",
                "\"Se vive bien en Espana.\" -- In Spanien lebt es sich gut.",
                "Wenn das Objekt eine Person ist, verwende \"a\" + Singularverb: \"Se busco a los responsables.\" -- Die Verantwortlichen wurden gesucht."
              ]
            },
            {
              "type": "rules",
              "items": [
                "Häufiger Fehler: \"Se buscan a los culpables.\" (Person + Plural = falsch)",
                "Korrekt: \"Se busca a los culpables.\" (Person -> Singular + persönliches a)"
              ]
            }
          ]
        },
        {
          "id": "3.2",
          "title": "Estar + Partizip (Resultatszustand) vs. Ser + Partizip (Vorgang)",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Konstruktion",
                "Fokus",
                "Beispiel"
              ],
              "rows": [
                [
                  "ser + participio",
                  "Die Handlung selbst (wer/was sie verursacht hat)",
                  "La ventana fue rota por el niño. -- Das Fenster wurde von dem Jungen zerbrochen."
                ],
                [
                  "estar + participio",
                  "Der resultierende Zustand",
                  "La ventana esta rota. -- Das Fenster ist kaputt."
                ]
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "El informe ya esta terminado.",
                  "en": "Der Bericht ist bereits fertig. (Zustand)"
                },
                {
                  "es": "El informe fue terminado ayer por el equipo.",
                  "en": "Der Bericht wurde gestern von dem Team fertiggestellt. (Vorgang)"
                },
                {
                  "es": "Las luces están encendidas.",
                  "en": "Das Licht ist an. (Zustand)"
                },
                {
                  "es": "Las luces fueron encendidas por el portero.",
                  "en": "Das Licht wurde von dem Pförtner eingeschaltet. (Vorgang)"
                }
              ]
            }
          ]
        },
        {
          "id": "3.3",
          "title": "Weitere unpersönliche Konstruktionen",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Konstruktion",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "uno/una",
                  "man (persönlich)",
                  "Uno nunca sabe que puede pasar."
                ],
                [
                  "la gente",
                  "die Leute",
                  "La gente no respeta las normas."
                ],
                [
                  "3. Person Plural (ohne Subjekt)",
                  "sie (unbestimmt)",
                  "Dicen que va a llover. -- Man sagt, es wird regnen."
                ],
                [
                  "hay que + Infinitiv",
                  "man muss",
                  "Hay que tener paciencia."
                ],
                [
                  "se debe + Infinitiv",
                  "man sollte",
                  "Se debe respetar a los demas."
                ],
                [
                  "conviene + Infinitiv",
                  "es empfiehlt sich",
                  "Conviene llegar temprano."
                ],
                [
                  "basta con + Infinitiv",
                  "es reicht zu",
                  "Basta con llamar para reservar."
                ]
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 3,
      "title": "Fortgeschrittene Zeitformen -- Nuancen",
      "sections": [
        {
          "id": "4.1",
          "title": "Das historische Präsens (Presente Histórico)",
          "blocks": [
            {
              "type": "text",
              "content": "Das Presente (Präsens) kann vergangene Ereignisse lebendig erzählen, so als würde der Hörer sie miterleben."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "En 1492, Colon llega a America.",
                  "en": "1492 kommt Kolumbus in Amerika an."
                },
                {
                  "es": "Estaba en casa tranquilo y, de repente, suena el teléfono y me dice que...",
                  "en": "Ich war ganz entspannt zu Hause, und plötzlich klingelt das Telefon und er sagt mir, dass..."
                }
              ]
            }
          ]
        },
        {
          "id": "4.2",
          "title": "Das Futur der Vermutung (Gegenwärtige Wahrscheinlichkeit)",
          "blocks": [
            {
              "type": "text",
              "content": "Das Futuro Simple (einfache Zukunft) drückt Spekulationen über die Gegenwart aus."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Donde estara Juan?",
                  "en": "Wo mag Juan sein? (frage ich mich)"
                },
                {
                  "es": "Serán las ocho.",
                  "en": "Es wird wohl acht Uhr sein."
                },
                {
                  "es": "Tendra unos cuarenta años.",
                  "en": "Er dürfte etwa vierzig Jahre alt sein."
                },
                {
                  "es": "Costara unos cien euros.",
                  "en": "Es kostet wahrscheinlich etwa hundert Euro."
                }
              ]
            }
          ]
        },
        {
          "id": "4.3",
          "title": "Das Konditional der Vermutung (Vergangene Wahrscheinlichkeit)",
          "blocks": [
            {
              "type": "text",
              "content": "Das Condicional (Konditional) drückt Spekulationen über die Vergangenheit aus."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Serian las tres cuando llegamos.",
                  "en": "Es muss etwa drei Uhr gewesen sein, als wir ankamen."
                },
                {
                  "es": "Tendria unos veinte años cuando se caso.",
                  "en": "Sie muss etwa zwanzig Jahre alt gewesen sein, als sie heiratete."
                },
                {
                  "es": "Estaria enfermo, por eso no vino.",
                  "en": "Er war wahrscheinlich krank, deshalb ist er nicht gekommen."
                }
              ]
            }
          ]
        },
        {
          "id": "4.4",
          "title": "Das vollendete Futur der Vermutung (Wahrscheinlichkeit in der jüngeren Vergangenheit)",
          "blocks": [
            {
              "type": "text",
              "content": "Das Futuro Perfecto (vollendete Zukunft) spekuliert über eine kürzlich abgeschlossene Handlung."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Ya habra llegado.",
                  "en": "Er wird inzwischen angekommen sein."
                },
                {
                  "es": "Que le habra pasado?",
                  "en": "Was mag ihm wohl passiert sein?"
                },
                {
                  "es": "Se habran perdido.",
                  "en": "Sie haben sich wahrscheinlich verlaufen."
                }
              ]
            }
          ]
        },
        {
          "id": "4.5",
          "title": "Das vollendete Konditional der Vermutung (Vorvergangenheits-Wahrscheinlichkeit)",
          "blocks": [
            {
              "type": "text",
              "content": "Das Condicional Compuesto (vollendetes Konditional) spekuliert über eine Handlung vor einem anderen vergangenen Ereignis."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Habrian salido antes de que empezara a llover.",
                  "en": "Sie müssen losgegangen sein, bevor es anfing zu regnen."
                },
                {
                  "es": "Habria terminado el trabajo antes de irse.",
                  "en": "Er muss die Arbeit beendet haben, bevor er ging."
                }
              ]
            }
          ]
        },
        {
          "id": "4.6",
          "title": "Temporalsätze mit zusammengesetzten Zeiten",
          "blocks": [
            {
              "type": "rules",
              "items": [
                "In Temporalsätzen, die sich auf die Zukunft beziehen, verwendest du den Subjuntivo (spanischer Konjunktiv) -- einschließlich zusammengesetzter Formen."
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Cuando hayas terminado, llamame.",
                  "en": "Wenn du fertig bist, rufe mich an. (Pretérito Perfecto de Subjuntivo)"
                },
                {
                  "es": "No salgas hasta que haya dejado de llover.",
                  "en": "Geh nicht raus, bis es aufgehört hat zu regnen."
                },
                {
                  "es": "En cuanto hayamos cenado, nos iremos.",
                  "en": "Sobald wir zu Abend gegessen haben, werden wir gehen."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 4,
      "title": "Relativsätze – Fortgeschritten",
      "sections": [
        {
          "id": "5.1",
          "title": "Der Subjuntivo (spanischer Konjunktiv) in Relativsätzen",
          "blocks": [
            {
              "type": "text",
              "content": "Der Modus in Relativsätzen hängt davon ab, ob das Bezugswort bekannt oder hypothetisch ist."
            },
            {
              "type": "rules",
              "items": [
                "Indikativ (bekanntes/existierendes Bezugswort): \"Tengo un amigo que habla japones.\" -- Ich habe einen Freund, der Japanisch spricht. (er existiert)"
              ]
            },
            {
              "type": "rules",
              "items": [
                "Subjuntivo (unbekanntes/nicht existierendes/gewünschtes Bezugswort):",
                "\"Busco a alguien que hable japones.\" -- Ich suche jemanden, der Japanisch spricht. (ich weiß nicht, ob es so jemanden gibt)",
                "\"Necesito un piso que tenga tres habitaciones.\" -- Ich brauche eine Wohnung, die drei Zimmer hat. (ich habe sie noch nicht gefunden)",
                "\"No hay nadie que sepa la respuesta.\" -- Es gibt niemanden, der die Antwort weiß."
              ]
            }
          ]
        },
        {
          "id": "5.2",
          "title": "El que / Quien bei Verallgemeinerungen",
          "blocks": [
            {
              "type": "text",
              "content": "\"El que\" / \"quien\" + Subjuntivo erzeugt Verallgemeinerungen (wer auch immer, jeder, der)."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "El que quiera participar, que levante la mano.",
                  "en": "Wer teilnehmen möchte, hebe die Hand."
                },
                {
                  "es": "Quien no este de acuerdo puede irse.",
                  "en": "Wer nicht einverstanden ist, kann gehen."
                },
                {
                  "es": "Los que lleguen tarde no podran entrar.",
                  "en": "Diejenigen, die zu spät kommen, werden nicht eintreten können."
                }
              ]
            }
          ]
        },
        {
          "id": "5.3",
          "title": "Lo que / Lo cual – Bezug auf ganze Sätze",
          "blocks": [
            {
              "type": "text",
              "content": "\"Lo que\" und \"lo cual\" beziehen sich auf eine ganze Aussage oder einen ganzen Satz zurück."
            },
            {
              "type": "rules",
              "items": [
                "\"Lo que\" ist vielseitig und gebräuchlich",
                "\"Lo cual\" wird nur in nicht-restriktiven (erklärenden) Sätzen verwendet und ist formaler"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Aprobo el examen, lo que nos alegro mucho.",
                  "en": "Er hat die Prüfung bestanden, was uns sehr gefreut hat."
                },
                {
                  "es": "No contesto al teléfono, lo cual me preocupo.",
                  "en": "Sie ging nicht ans Telefon, was mich beunruhigt hat."
                },
                {
                  "es": "Lo que necesitas es descansar.",
                  "en": "Was du brauchst, ist dich auszuruhen."
                }
              ]
            }
          ]
        },
        {
          "id": "5.4",
          "title": "Cuyo/a/os/as – „dessen / deren“",
          "blocks": [
            {
              "type": "text",
              "content": "\"Cuyo\" richtet sich nach dem Substantiv, das besessen wird, nicht nach dem Besitzer. Es ist formal und kommt eher in der Schriftsprache vor."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "El autor cuyo libro gano el premio es chileno.",
                  "en": "Der Autor, dessen Buch den Preis gewonnen hat, ist Chilene."
                },
                {
                  "es": "La empresa cuyas oficinas visitamos esta en crisis.",
                  "en": "Das Unternehmen, dessen Büros wir besucht haben, steckt in der Krise."
                },
                {
                  "es": "Los paises cuyos gobiernos invirtieron en educación prosperaron.",
                  "en": "Die Länder, deren Regierungen in Bildung investierten, florierten."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 5,
      "title": "Erweiterte Verbperiphrasen",
      "sections": [
        {
          "id": "6.1",
          "title": "Periphrasen mit Infinitiv",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Periphrase",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "deber + inf.",
                  "Verpflichtung / moralische Pflicht",
                  "Debes ser mas puntual."
                ],
                [
                  "deber de + inf.",
                  "Wahrscheinlichkeit / Vermutung",
                  "Debe de estar en casa."
                ],
                [
                  "tener que + inf.",
                  "starke Verpflichtung",
                  "Tengo que irme ya."
                ],
                [
                  "haber de + inf.",
                  "leichte Verpflichtung / Erwartung (literarisch)",
                  "Has de saber que no fue fácil."
                ],
                [
                  "haber que + inf.",
                  "unpersönliche Verpflichtung",
                  "Hay que tener cuidado."
                ],
                [
                  "venir a + inf.",
                  "schließlich tun / etwa, ungefähr",
                  "Viene a costar unos cien euros."
                ],
                [
                  "llegar a + inf.",
                  "schaffen zu / so weit kommen, dass",
                  "Llego a ser presidente."
                ],
                [
                  "alcanzar a + inf.",
                  "gerade noch schaffen",
                  "No alcance a verle."
                ],
                [
                  "acertar a + inf.",
                  "zufällig tun / schaffen zu",
                  "No acerto a decir nada."
                ],
                [
                  "echarse a + inf.",
                  "plötzlich beginnen zu",
                  "Se echo a llorar."
                ],
                [
                  "romper a + inf.",
                  "plötzlich beginnen zu (nachdrücklich)",
                  "Rompio a reir."
                ],
                [
                  "ponerse a + inf.",
                  "beginnen (spontan)",
                  "Se puso a llover."
                ],
                [
                  "meterse a + inf.",
                  "sich einlassen auf",
                  "Se metio a arreglar la casa."
                ],
                [
                  "tardar en + inf.",
                  "brauchen für / Zeit benötigen",
                  "Tardo en contestar."
                ],
                [
                  "acabar por + inf.",
                  "schließlich tun",
                  "Acabo por aceptar."
                ],
                [
                  "dejar de + inf.",
                  "aufhören zu",
                  "Dejo de fumar hace un ano."
                ],
                [
                  "no dejar de + inf.",
                  "nicht versäumen zu / unbedingt tun",
                  "No dejes de visitar el museo."
                ],
                [
                  "pasar a + inf.",
                  "übergehen zu",
                  "Pasemos a analizar los datos."
                ]
              ]
            }
          ]
        },
        {
          "id": "6.2",
          "title": "Periphrasen mit dem Gerundio (Verlaufsform auf -ando/-iendo)",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Periphrase",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "estar + gerundio",
                  "Handlung im Gange",
                  "Estoy trabajando."
                ],
                [
                  "seguir / continuar + gerundio",
                  "weitermachen",
                  "Sigue lloviendo."
                ],
                [
                  "llevar + Zeitangabe + gerundio",
                  "seit ... Zeit etwas tun",
                  "Llevo tres horas esperando."
                ],
                [
                  "ir + gerundio",
                  "allmähliche Entwicklung",
                  "Va mejorando poco a poco."
                ],
                [
                  "venir + gerundio",
                  "fortlaufend von der Vergangenheit bis zur Gegenwart",
                  "Viene quejandose desde hace meses."
                ],
                [
                  "andar + gerundio",
                  "ständig / dauernd etwas tun (umgangssprachlich/negativ)",
                  "Anda diciendo mentiras."
                ],
                [
                  "quedarse + gerundio",
                  "in einer Handlung verharren",
                  "Se quedo mirandome sin decir nada."
                ],
                [
                  "acabar / terminar + gerundio",
                  "am Ende doch tun",
                  "Acabe aceptando la oferta."
                ],
                [
                  "salir + gerundio",
                  "als Ergebnis herauskommen (oft unerwartet)",
                  "Salio ganando al final."
                ]
              ]
            }
          ]
        },
        {
          "id": "6.3",
          "title": "Periphrasen mit dem Participio (Partizip)",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Periphrase",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "tener + participio",
                  "abgeschlossenes Ergebnis (Partizip gleicht sich an)",
                  "Tengo hechos los deberes."
                ],
                [
                  "llevar + participio",
                  "angesammelte Gesamtmenge (Partizip gleicht sich an)",
                  "Llevo leídos tres capitulos."
                ],
                [
                  "dejar + participio",
                  "in einem Zustand hinterlassen (Partizip gleicht sich an)",
                  "Deje la puerta cerrada."
                ],
                [
                  "quedar + participio",
                  "in einem Zustand verbleiben",
                  "La cena quedo preparada."
                ],
                [
                  "dar por + participio",
                  "betrachten als",
                  "Doy por terminada la reunion."
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "In diesen Konstruktionen stimmt das Participio in Genus und Numerus mit dem direkten Objekt (Akkusativobjekt) überein."
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Tengo escritas tres cartas.",
                  "en": "Ich habe drei Briefe fertig geschrieben. (cartas = fem. Pl.)"
                },
                {
                  "es": "Llevo leidas cien paginas.",
                  "en": "Ich habe bisher hundert Seiten gelesen."
                },
                {
                  "es": "Damos por cerrado el debate.",
                  "en": "Wir betrachten die Debatte als beendet."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 6,
      "title": "Erweitertes Ser vs. Estar",
      "sections": [
        {
          "id": "7.1",
          "title": "Estar für subjektive/vorübergehende Wahrnehmung vs. Ser für objektive Klassifizierung",
          "blocks": [
            {
              "type": "text",
              "content": "Auf Niveau C1 beherrschst du die Verwendung von estar, um eine subjektive Reaktion, Überraschung oder eine wahrnehmbare Veränderung auszudrücken."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Que guapa estas hoy!",
                  "en": "Wie hübsch du heute aussiehst! (wahrnehmbare Veränderung)"
                },
                {
                  "es": "El niño esta muy alto.",
                  "en": "Der Junge ist (jetzt) sehr groß. (wahrgenommenes Wachstum)"
                },
                {
                  "es": "Esta sopa esta muy salada.",
                  "en": "Diese Suppe ist sehr salzig. (jetzt probiert, subjektiv)"
                },
                {
                  "es": "La habitación esta muy pequeña con todos estos muebles.",
                  "en": "Das Zimmer wirkt mit all diesen Möbeln sehr klein. (subjektiver Eindruck)"
                }
              ]
            }
          ]
        },
        {
          "id": "7.2",
          "title": "Ser bei Veranstaltungen und Veranstaltungsorten",
          "blocks": [
            {
              "type": "text",
              "content": "\"Ser\" wird für den Ort von Veranstaltungen verwendet (nicht für Gegenstände/Personen)."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "La reunion es en la sala 3.",
                  "en": "Das Meeting ist in Raum 3."
                },
                {
                  "es": "La fiesta será en mi casa.",
                  "en": "Die Party wird bei mir zu Hause stattfinden."
                },
                {
                  "es": "El concierto fue en el estadio.",
                  "en": "Das Konzert war im Stadion."
                }
              ]
            },
            {
              "type": "text",
              "content": "Vergleiche mit estar für Gegenstände/Personen: \"Juan esta en la sala 3.\" -- Juan ist in Raum 3."
            }
          ]
        },
        {
          "id": "7.3",
          "title": "Ser/Estar + das Participio (Partizip) -- Gesamtsystem",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Konstruktion",
                "Bedeutung",
                "Kongruenz",
                "Beispiel"
              ],
              "rows": [
                [
                  "ser + participio",
                  "Vorgangspassiv (durch Agens)",
                  "stimmt mit dem Subjekt überein",
                  "El libro fue escrito por Cervantes."
                ],
                [
                  "estar + participio",
                  "Zustandspassiv",
                  "stimmt mit dem Subjekt überein",
                  "El libro esta escrito en español."
                ],
                [
                  "tener + participio",
                  "abgeschlossene Handlung mit Schwerpunkt auf dem Ergebnis",
                  "stimmt mit dem direkten Objekt (Akkusativobjekt) überein",
                  "Tengo leidas tres novelas."
                ],
                [
                  "llevar + participio",
                  "angesammeltes Ergebnis",
                  "stimmt mit dem direkten Objekt (Akkusativobjekt) überein",
                  "Llevo escritas cinco paginas."
                ]
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 7,
      "title": "Diskurs und Textorganisation",
      "sections": [
        {
          "id": "8.1",
          "title": "Erweiterte Konnektoren nach Funktion",
          "blocks": [
            {
              "type": "text",
              "content": "Ein Thema einleiten:"
            },
            {
              "type": "rules",
              "items": [
                "En cuanto a... / En lo que se refiere a... / Con respecto a... / En relación con...",
                "\"En cuanto a la economia, la situación ha mejorado.\" -- Bezüglich der Wirtschaft hat sich die Situation verbessert."
              ]
            },
            {
              "type": "text",
              "content": "Informationen hinzufügen:"
            },
            {
              "type": "rules",
              "items": [
                "Además / Asimismo / Por otra parte / Es mas / Incluso / No solo... sino también",
                "\"Es mas, el informe demuestra que los resultados son positivos.\" -- Darüber hinaus zeigt der Bericht, dass die Ergebnisse positiv sind."
              ]
            },
            {
              "type": "text",
              "content": "Kontrastieren:"
            },
            {
              "type": "rules",
              "items": [
                "Sin embargo / No obstante / Ahora bien / En cambio / Por el contrario / Con todo",
                "\"Con todo, hay que reconocer que el esfuerzo ha valido la pena.\" -- Trotz allem muss man anerkennen, dass sich die Mühe gelohnt hat."
              ]
            },
            {
              "type": "text",
              "content": "Folgen ausdrücken:"
            },
            {
              "type": "rules",
              "items": [
                "Por lo tanto / Por consiguiente / En consecuencia / De ahí que (+ Subjuntivo) / Así pues",
                "\"De ahí que muchos jovenes emigren.\" -- Daher wandern viele junge Menschen aus. (Subjuntivo)"
              ]
            },
            {
              "type": "text",
              "content": "Umformulieren:"
            },
            {
              "type": "rules",
              "items": [
                "Es decir / O sea / En otras palabras / Mejor dicho / Dicho de otro modo",
                "\"Mejor dicho, no es que no quiera, sino que no puede.\" -- Genauer gesagt, es ist nicht so, dass er nicht will, sondern dass er nicht kann."
              ]
            },
            {
              "type": "text",
              "content": "Zusammenfassen / Folgern:"
            },
            {
              "type": "rules",
              "items": [
                "En resumen / En conclusión / En definitiva / Para terminar / En pocas palabras / Al fin y al cabo",
                "\"Al fin y al cabo, lo importante es que estamos juntos.\" -- Letzten Endes ist das Wichtige, dass wir zusammen sind."
              ]
            }
          ]
        },
        {
          "id": "8.2",
          "title": "De ahí que + Subjuntivo",
          "blocks": [
            {
              "type": "text",
              "content": "\"De ahí que\" leitet eine Konsequenz ein und verlangt immer den Subjuntivo (spanischer Konjunktiv)."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "No estudio lo suficiente; de ahí que suspendiera.",
                  "en": "Er hat nicht genug gelernt; daher ist er durchgefallen."
                },
                {
                  "es": "La situación es complicada; de ahí que necesitemos mas tiempo.",
                  "en": "Die Situation ist kompliziert; daher brauchen wir mehr Zeit."
                }
              ]
            }
          ]
        },
        {
          "id": "8.3",
          "title": "Abschwächen und vorsichtig formulieren",
          "blocks": [
            {
              "type": "text",
              "content": "C1-Sprecher schwächen Meinungen und Aussagen aus Höflichkeit und Präzision ab."
            },
            {
              "type": "table",
              "headers": [
                "Ausdruck",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "Diria que...",
                  "Ich würde sagen, dass...",
                  "Diria que es una buena idea."
                ],
                [
                  "Me atreveria a decir que...",
                  "Ich würde es wagen zu sagen, dass...",
                  "Me atreveria a decir que es el mejor."
                ],
                [
                  "En mi opinion / A mi juicio",
                  "Meiner Meinung nach",
                  "A mi juicio, deberiamos esperar."
                ],
                [
                  "Por lo visto / Segun parece",
                  "Anscheinend",
                  "Por lo visto, van a cerrar la empresa."
                ],
                [
                  "Que yo sepa",
                  "Soweit ich weiß",
                  "Que yo sepa, no han cambiado nada."
                ],
                [
                  "Al parecer",
                  "Anscheinend",
                  "Al parecer, el director ha dimitido."
                ],
                [
                  "Cabe senalar que",
                  "Es ist erwähnenswert, dass",
                  "Cabe senalar que los datos son incompletos."
                ]
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 8,
      "title": "Substantivsätze – Fortgeschrittene Muster",
      "sections": [
        {
          "id": "9.1",
          "title": "Verben der Kommunikation + Indikativ/Subjuntivo",
          "blocks": [
            {
              "type": "text",
              "content": "Der Modus hängt davon ab, ob das Verb Information oder Einfluss vermittelt."
            },
            {
              "type": "rules",
              "items": [
                "Indikativ (Informationen berichten): decir, afirmar, declarar, confesar, reconocer, admitir + que + Indikativ",
                "\"Dice que viene mañana.\" -- Er sagt, dass er morgen kommt.",
                "\"Reconocio que se había equivocado.\" -- Er gab zu, dass er sich geirrt hatte."
              ]
            },
            {
              "type": "rules",
              "items": [
                "Subjuntivo (Einfluss ausüben / Befehl): decir, pedir, ordenar, rogar, exigir, suplicar + que + subjuntivo",
                "\"Dice que vengas mañana.\" -- Er sagt, du sollst morgen kommen.",
                "\"Le pidio que se callara.\" -- Er bat ihn zu schweigen."
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Le dijo que estaba enfermo.",
                  "en": "Er sagte ihm, dass er krank war. (Information -> Indikativ)"
                },
                {
                  "es": "Le dijo que fuera al medico.",
                  "en": "Er sagte ihm, er solle zum Arzt gehen. (Befehl -> Subjuntivo)"
                }
              ]
            }
          ]
        },
        {
          "id": "9.2",
          "title": "Verben des Denkens/Glaubens – Moduswechsel",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Bejahend (Indikativ)",
                "Verneint (Subjuntivo)"
              ],
              "rows": [
                [
                  "Creo que es verdad.",
                  "No creo que sea verdad."
                ],
                [
                  "Pienso que tiene razon.",
                  "No pienso que tenga razon."
                ],
                [
                  "Me parece que esta bien.",
                  "No me parece que este bien."
                ],
                [
                  "Estoy seguro de que vendra.",
                  "No estoy seguro de que venga."
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "In Fragen (hängt von der erwarteten Antwort ab):",
                "\"Crees que es verdad?\" -- Glaubst du, dass es wahr ist? (neutral -> Indikativ)",
                "\"No crees que sea verdad?\" -- Glaubst du nicht, dass es wahr sein könnte? (Zweifel -> Subjuntivo)"
              ]
            }
          ]
        },
        {
          "id": "9.3",
          "title": "El hecho de que + Indikativ/Subjuntivo",
          "blocks": [
            {
              "type": "text",
              "content": "\"El hecho de que\" (die Tatsache, dass) kann beide Modi annehmen: Indikativ, wenn du es als feststehende Tatsache betrachtest, Subjuntivo, wenn du ein Urteil hinzufügst oder wenn der Nebensatz eine neue Information ist."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "El hecho de que trabaja mucho es evidente.",
                  "en": "Die Tatsache, dass er viel arbeitet, ist offensichtlich. (feststehend)"
                },
                {
                  "es": "El hecho de que trabaje mucho no significa que sea eficiente.",
                  "en": "Die Tatsache, dass er viel arbeitet, bedeutet nicht, dass er effizient ist. (Urteil)"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 9,
      "title": "Wortstellung und Betonung",
      "sections": [
        {
          "id": "10.1",
          "title": "Topikalisierung (Voranstellung)",
          "blocks": [
            {
              "type": "text",
              "content": "Du stellst ein Element an den Satzanfang, um es zu betonen oder als Thema zu setzen."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Eso no lo sabia.",
                  "en": "Das wusste ich nicht. (vorgestelltes direktes Objekt mit redundantem Pronomen)"
                },
                {
                  "es": "A Juan le regale un libro.",
                  "en": "Juan habe ich ein Buch geschenkt. (vorgestelltes indirektes Objekt)"
                },
                {
                  "es": "En esa casa vivieron mis abuelos.",
                  "en": "In diesem Haus haben meine Großeltern gewohnt. (vorgestellte adverbiale Bestimmung)"
                },
                {
                  "es": "Cansado estoy, pero no me rindo.",
                  "en": "Müde bin ich, aber ich gebe nicht auf. (vorgestelltes Prädikat)"
                }
              ]
            }
          ]
        },
        {
          "id": "10.2",
          "title": "Spaltsätze (Oraciones Hendidas)",
          "blocks": [
            {
              "type": "text",
              "content": "Wird verwendet, um ein bestimmtes Element des Satzes hervorzuheben."
            },
            {
              "type": "rules",
              "items": [
                "Struktur: Ser + hervorgehobenes Element + el/la/lo que/quien + Rest"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Fue Juan el que lo hizo.",
                  "en": "Es war Juan, der es getan hat."
                },
                {
                  "es": "Es la economia lo que mas me preocupa.",
                  "en": "Es ist die Wirtschaft, die mir am meisten Sorgen macht."
                },
                {
                  "es": "Fueron ellos quienes decidieron.",
                  "en": "Sie waren es, die entschieden haben."
                },
                {
                  "es": "Es aquí donde todo empezo.",
                  "en": "Es ist hier, wo alles begann."
                }
              ]
            }
          ]
        },
        {
          "id": "10.3",
          "title": "Reduplikation zur Betonung",
          "blocks": [
            {
              "type": "text",
              "content": "Wiederholung eines Wortes zur Verstärkung."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Lo que es es.",
                  "en": "Es ist, was es ist."
                },
                {
                  "es": "Eso si que es verdad.",
                  "en": "Das ist wirklich wahr."
                },
                {
                  "es": "Trabajar, trabajamos mucho.",
                  "en": "Was das Arbeiten angeht, arbeiten wir viel. (Infinitiv vorangestellt + konjugierte Form)"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 10,
      "title": "Fortgeschrittene Verwendungen von „Se“",
      "sections": [
        {
          "id": "11.1",
          "title": "Vollständige Bestandsaufnahme von „Se“",
          "blocks": [
            {
              "type": "text",
              "content": "Auf Niveau C1 musst du alle Funktionen von „se“ erkennen."
            },
            {
              "type": "table",
              "headers": [
                "Funktion",
                "Beispiel",
                "Erklärung"
              ],
              "rows": [
                [
                  "Reflexiv",
                  "Se lava las manos.",
                  "Er wäscht sich die (eigenen) Hände."
                ],
                [
                  "Reziprok",
                  "Se quieren mucho.",
                  "Sie lieben sich gegenseitig."
                ],
                [
                  "Passives se",
                  "Se venden pisos.",
                  "Wohnungen werden verkauft."
                ],
                [
                  "Unpersönliches se",
                  "Se vive bien aquí.",
                  "Man lebt hier gut."
                ],
                [
                  "Pronominales Verb",
                  "Se arrepintio.",
                  "Er hat es bereut. (inhärentes se)"
                ],
                [
                  "Ersetzung des indirekten Objekts",
                  "Se lo di. (= le lo di)",
                  "Ich habe es ihm gegeben."
                ],
                [
                  "Aspektuelles / intensives se",
                  "Se comio toda la pizza.",
                  "Er hat die ganze Pizza aufgegessen. (emphatische Vollendung)"
                ],
                [
                  "Dativ des Interesses",
                  "Se me cayo el vaso.",
                  "Das Glas ist mir heruntergefallen. (unfreiwillig)"
                ]
              ]
            }
          ]
        },
        {
          "id": "11.2",
          "title": "Unfreiwilliges / Unabsichtliches „Se“ (Se me / Se te / Se le...)",
          "blocks": [
            {
              "type": "text",
              "content": "Diese Konstruktion nimmt dem Subjekt die Schuld und stellt die Handlung als unabsichtlich oder unfreiwillig dar."
            },
            {
              "type": "rules",
              "items": [
                "Struktur: Se + indirektes Objektspronomen + Verb (3. Person, stimmt mit der Sache überein) + Subjekt (Sache)"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Se me olvidaron las llaves.",
                  "en": "Ich habe die Schlüssel vergessen. (wörtl.: Die Schlüssel sind mir entfallen.)"
                },
                {
                  "es": "Se le rompio el teléfono.",
                  "en": "Sein Telefon ging kaputt. (unfreiwillig)"
                },
                {
                  "es": "Se nos acabo el tiempo.",
                  "en": "Uns ist die Zeit ausgegangen."
                },
                {
                  "es": "Se te cayo el cafe.",
                  "en": "Dir ist der Kaffee heruntergefallen."
                },
                {
                  "es": "Se me ha ocurrido una idea.",
                  "en": "Mir ist eine Idee gekommen."
                }
              ]
            },
            {
              "type": "text",
              "content": "Häufige Verben in dieser Konstruktion: olvidar, romper, perder, caer, acabar, ocurrir, escapar, quemar, estropear"
            }
          ]
        },
        {
          "id": "11.3",
          "title": "Aspektuelles / Intensives „Se“ (Se comio, se bebio...)",
          "blocks": [
            {
              "type": "text",
              "content": "Das Hinzufügen von „se“ zu bestimmten transitiven Verben betont die Vollständigkeit der Handlung."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Comio una pizza.",
                  "en": "Er aß eine Pizza. (neutral)"
                },
                {
                  "es": "Se comio toda la pizza.",
                  "en": "Er aß die ganze Pizza auf. (Vollständigkeit betont)"
                },
                {
                  "es": "Leyo el libro.",
                  "en": "Sie las das Buch. (neutral)"
                },
                {
                  "es": "Se leyo el libro entero en una noche.",
                  "en": "Sie las das ganze Buch in einer Nacht durch. (emphatisch)"
                },
                {
                  "es": "Bebio tres cervezas.",
                  "en": "Er trank drei Biere."
                },
                {
                  "es": "Se bebio tres cervezas de un trago.",
                  "en": "Er trank drei Biere in einem Zug aus."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 11,
      "title": "Register und Stil",
      "sections": [
        {
          "id": "12.1",
          "title": "Formelles vs. informelles Register",
          "blocks": [
            {
              "type": "text",
              "content": "C1-Sprecher passen ihre Sprache je nach Kontext an."
            },
            {
              "type": "table",
              "headers": [
                "Merkmal",
                "Informell",
                "Formell"
              ],
              "rows": [
                [
                  "Anrede",
                  "tu / vosotros",
                  "usted / ustedes"
                ],
                [
                  "Begrüßung",
                  "Hola! Que tal?",
                  "Buenos días. Como esta usted?"
                ],
                [
                  "Bitten",
                  "Me ayudas?",
                  "Seria tan amable de ayudarme?"
                ],
                [
                  "Ausdrücke",
                  "la verdad es que...",
                  "cabe destacar que..."
                ],
                [
                  "Konnektoren",
                  "o sea, bueno, pues",
                  "es decir, por consiguiente"
                ],
                [
                  "Subjuntivo in -ra vs. -se",
                  "-ra-Form vorherrschend",
                  "-se-Form kommt ebenfalls vor"
                ],
                [
                  "Wortschatz",
                  "curro (Arbeit), molar (cool sein)",
                  "trabajo, resultar agradable"
                ]
              ]
            }
          ]
        },
        {
          "id": "12.2",
          "title": "Umgangssprachliche Verstärkungen und Marker",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Ausdruck",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "Que va!",
                  "Von wegen! / Ach was!",
                  "Estas enfadado? -- Que va!"
                ],
                [
                  "Venga!",
                  "Los! / Na los! / Alles klar!",
                  "Venga, vamonos!"
                ],
                [
                  "Anda!",
                  "Ach was! / Wow! / Na komm!",
                  "Anda, no lo sabia!"
                ],
                [
                  "o sea",
                  "das heißt / sprich",
                  "O sea, no me parece bien."
                ],
                [
                  "bueno",
                  "nun / tja",
                  "Bueno, que hacemos?"
                ],
                [
                  "pues",
                  "nun / also",
                  "Pues no se que decirte."
                ],
                [
                  "es que",
                  "die Sache ist die / es ist so, dass",
                  "Es que no tengo tiempo."
                ],
                [
                  "total que",
                  "jedenfalls / kurzum",
                  "Total que nos quedamos en casa."
                ],
                [
                  "resulta que",
                  "es stellt sich heraus, dass",
                  "Resulta que ya lo sabia."
                ]
              ]
            }
          ]
        },
        {
          "id": "12.3",
          "title": "Euphemismen und Höflichkeitsstrategien",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Direkt",
                "Abgeschwächt"
              ],
              "rows": [
                [
                  "No puedo.",
                  "Me resulta imposible / Me temo que no va a ser posible."
                ],
                [
                  "Estas equivocado.",
                  "Creo que habria que reconsiderar esa idea."
                ],
                [
                  "Es malo.",
                  "No es del todo satisfactorio / Deja bastante que desear."
                ],
                [
                  "Dime la verdad.",
                  "Me gustaria que fueras sincero conmigo."
                ],
                [
                  "Hazlo.",
                  "Te importaria hacerlo? / Serias tan amable de...?"
                ]
              ]
            }
          ]
        }
      ]
    }
  ]
}
