import { GrammarLevel } from './types'

// GENERATED by scripts/translate-grammar.ts — reviewed and corrected by hand.
// German explanations, Spanish examples untouched. Example `en` fields hold the
// German gloss (the Block renderer shows that field as the secondary line).
// Re-running the script will NOT clobber this file's cache; delete
// scripts/.cache/grammar-de/c2-*.json to force a re-translation.
export const grammarC2De: GrammarLevel = {
  "level": "C2",
  "title": "Spanische Grammatik — Meisterklasse",
  "chapters": [
    {
      "id": 0,
      "title": "Der Subjuntivo (spanischer Konjunktiv) — Meisterschaft",
      "sections": [
        {
          "id": "1.1",
          "title": "Der Subjuntivo in festen und idiomatischen Ausdrücken",
          "blocks": [
            {
              "type": "text",
              "content": "Auf C2-Niveau erscheint der Subjuntivo in zahlreichen festen Ausdrücken, Sprichwörtern und idiomatischen Konstruktionen, die du erkennen und natürlich anwenden musst."
            },
            {
              "type": "table",
              "headers": [
                "Ausdruck",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "sea como sea",
                  "wie dem auch sei",
                  "Sea como sea, hay que terminarlo."
                ],
                [
                  "diga lo que diga",
                  "was auch immer er/sie sagt",
                  "Diga lo que diga, no cambiaré de opinión."
                ],
                [
                  "pase lo que pase",
                  "was auch immer passiert",
                  "Pase lo que pase, estaré aquí."
                ],
                [
                  "venga lo que venga",
                  "komme, was wolle",
                  "Venga lo que venga, estamos preparados."
                ],
                [
                  "cueste lo que cueste",
                  "kostet es, was es wolle",
                  "Lo conseguiré, cueste lo que cueste."
                ],
                [
                  "que yo sepa",
                  "sofern ich weiß",
                  "Que yo sepa, no ha dimitido."
                ],
                [
                  "que yo recuerde",
                  "soweit ich mich erinnere",
                  "Que yo recuerde, nunca dijo eso."
                ],
                [
                  "que digamos",
                  "gerade (abschwächend, meist nach Verneinung)",
                  "No es muy amable que digamos."
                ],
                [
                  "no sea que / no vaya a ser que",
                  "damit nicht / für den Fall, dass",
                  "Lleva paraguas, no sea que llueva."
                ],
                [
                  "así sea",
                  "so sei es / Amen",
                  "Así sea."
                ]
              ]
            },
            {
              "type": "table",
              "headers": [
                "Muster",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "quien + subj. + quien + subj.",
                  "wer auch immer",
                  "Quien quiera que sea, no abras la puerta."
                ],
                [
                  "donde + subj. + donde + subj.",
                  "wo auch immer",
                  "Dondequiera que vayas, te encontraré."
                ],
                [
                  "como + subj. + como + subj.",
                  "wie auch immer",
                  "Comoquiera que lo hagas, estará bien."
                ],
                [
                  "cuando + subj. + cuando + subj.",
                  "wann auch immer",
                  "Cuando quiera que vengas, serás bienvenido."
                ]
              ]
            }
          ]
        },
        {
          "id": "1.2",
          "title": "Das Futuro de Subjuntivo auf -re (Zukunft des Subjuntivo)",
          "blocks": [
            {
              "type": "text",
              "content": "Das Futuro de Subjuntivo ist im alltäglichen Spanisch archaisch, überlebt aber in Rechtstexten, Sprichwörtern und einigen festen Ausdrücken. C2-Lernende sollten es erkennen."
            },
            {
              "type": "text",
              "content": "Bildung: gleicher Stamm wie das Imperfecto de Subjuntivo (-ra-Form), mit den Endungen: -re, -res, -re, -remos, -reis, -ren"
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "hablar",
                "tener",
                "ser/ir"
              ],
              "rows": [
                [
                  "yo",
                  "hablare",
                  "tuviere",
                  "fuere"
                ],
                [
                  "tú",
                  "hablares",
                  "tuvieres",
                  "fueres"
                ],
                [
                  "él/ella/usted",
                  "hablare",
                  "tuviere",
                  "fuere"
                ],
                [
                  "nosotros/as",
                  "habláremos",
                  "tuviéremos",
                  "fuéremos"
                ],
                [
                  "vosotros/as",
                  "hablareis",
                  "tuviereis",
                  "fuereis"
                ],
                [
                  "ellos/ellas/ustedes",
                  "hablaren",
                  "tuvieren",
                  "fueren"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "Rechtssprache: \"El que infringiere esta ley será sancionado.\" — Wer dieses Gesetz verletzt, wird bestraft.",
                "Sprichwörter: \"Adonde fueres, haz lo que vieres.\" — Andere Länder, andere Sitten.",
                "Feste Ausdrücke: \"Sea lo que fuere.\" — Wie dem auch sei."
              ]
            }
          ]
        },
        {
          "id": "1.3",
          "title": "Wechsel zwischen Indikativ und Subjuntivo in nuancierten Kontexten",
          "blocks": [
            {
              "type": "text",
              "content": "Auf C2-Niveau musst du mit Grenzfällen umgehen, bei denen beide Modi verwendet werden können, mit subtilen Bedeutungsunterschieden."
            },
            {
              "type": "text",
              "content": "\"El hecho de que\":"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "El hecho de que trabaja mucho es evidente.",
                  "en": "Indikativ — feststehende Tatsache"
                },
                {
                  "es": "El hecho de que trabaje tanto no justifica su comportamiento.",
                  "en": "Subjuntivo — bewertender Kontext"
                }
              ]
            },
            {
              "type": "text",
              "content": "\"No es que\" (immer Subjuntivo):"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "No es que no quiera, es que no puedo.",
                  "en": "Es ist nicht so, dass ich nicht will, es ist so, dass ich nicht kann."
                }
              ]
            },
            {
              "type": "text",
              "content": "\"Parece que\" vs. \"No parece que\":"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Parece que va a llover.",
                  "en": "Es sieht so aus, als würde es regnen. (Indikativ)"
                },
                {
                  "es": "No parece que vaya a llover.",
                  "en": "Es sieht nicht so aus, als würde es regnen. (Subjuntivo)"
                }
              ]
            },
            {
              "type": "text",
              "content": "\"Según\" (je nach Gewissheit):"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Según dicen, va a llover.",
                  "en": "Wie man sagt, wird es regnen. (Indikativ — wiedergegebene Tatsache)"
                },
                {
                  "es": "Según sea necesario.",
                  "en": "Je nach Bedarf. (Subjuntivo — Eventualität)"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 1,
      "title": "Das vollständige System der Zeiten und Modi — Integrierte Beherrschung",
      "sections": [
        {
          "id": "2.1",
          "title": "Vollständige Übersicht der Zeiten und Modi",
          "blocks": [
            {
              "type": "text",
              "content": "C2 erfordert, dass du jede Kombination aus Zeitform und Modus vollständig beherrschst."
            },
            {
              "type": "text",
              "content": "Zeiten des Indikativs:"
            },
            {
              "type": "table",
              "headers": [
                "Zeitform",
                "Beispiel (hablar)",
                "Hauptsächliche Verwendung"
              ],
              "rows": [
                [
                  "das Presente (Präsens)",
                  "hablo",
                  "Aktuelle Handlungen, Gewohnheiten, allgemeine Wahrheiten"
                ],
                [
                  "das Imperfecto (Verlaufsvergangenheit)",
                  "hablaba",
                  "Gewohnheiten in der Vergangenheit, Beschreibung, andauernde Vergangenheit"
                ],
                [
                  "das Indefinido (einfache Vergangenheit)",
                  "hablé",
                  "Abgeschlossene Handlungen in der Vergangenheit"
                ],
                [
                  "das Pretérito Perfecto (Perfekt)",
                  "he hablado",
                  "Kürzliche Vergangenheit, Verbindung zur Gegenwart"
                ],
                [
                  "das Pluscuamperfecto (Plusquamperfekt)",
                  "había hablado",
                  "Vergangenheit vor einer anderen Vergangenheit"
                ],
                [
                  "das Futuro Simple (einfache Zukunft)",
                  "hablaré",
                  "Zukunft, Vermutung über die Gegenwart"
                ],
                [
                  "das Futuro Perfecto (vollendete Zukunft)",
                  "habré hablado",
                  "Vollendete Zukunft, Vermutung über die kürzliche Vergangenheit"
                ],
                [
                  "das Condicional (Konditional)",
                  "hablaría",
                  "Hypothetisches, Höflichkeit, Vermutung über die Vergangenheit"
                ],
                [
                  "das Condicional Compuesto (vollendeter Konditional)",
                  "habría hablado",
                  "Irreales in der Vergangenheit, Vermutung über die ferne Vergangenheit"
                ]
              ]
            },
            {
              "type": "text",
              "content": "Zeiten des Subjuntivo:"
            },
            {
              "type": "table",
              "headers": [
                "Zeitform",
                "Beispiel (hablar)",
                "Hauptsächliche Verwendung"
              ],
              "rows": [
                [
                  "das Presente",
                  "hable",
                  "Kontexte des Subjuntivo in der Gegenwart/Zukunft"
                ],
                [
                  "das Imperfecto (-ra/-se)",
                  "hablara / hablase",
                  "Subjuntivo der Vergangenheit, Hypothetisches"
                ],
                [
                  "das Pretérito Perfecto",
                  "haya hablado",
                  "Abgeschlossene Handlung im Kontext des Subjuntivo"
                ],
                [
                  "das Pluscuamperfecto",
                  "hubiera/hubiese hablado",
                  "Irreales im Subjuntivo der Vergangenheit"
                ],
                [
                  "das Futuro (archaisch)",
                  "hablare",
                  "Rechtssprache/literarisch/sprichwörtlich"
                ]
              ]
            },
            {
              "type": "text",
              "content": "Der Imperativo (Befehlsform):"
            },
            {
              "type": "table",
              "headers": [
                "Form",
                "Beispiel"
              ],
              "rows": [
                [
                  "tú (bejahend)",
                  "habla"
                ],
                [
                  "tú (verneinend)",
                  "no hables"
                ],
                [
                  "usted",
                  "hable / no hable"
                ],
                [
                  "nosotros",
                  "hablemos / no hablemos"
                ],
                [
                  "vosotros (bejahend)",
                  "hablad"
                ],
                [
                  "vosotros (verneinend)",
                  "no habléis"
                ],
                [
                  "ustedes",
                  "hablen / no hablen"
                ]
              ]
            }
          ]
        },
        {
          "id": "2.2",
          "title": "Die -ra-Form als Alternative zum Condicional",
          "blocks": [
            {
              "type": "text",
              "content": "Im literarischen und journalistischen Spanisch kann das Imperfecto des Subjuntivo auf -ra das Condicional oder das Pluscuamperfecto des Indikativs ersetzen."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Quisiera hablar contigo.",
                  "en": "Querría hablar contigo. — Ich möchte gerne mit dir sprechen. (höflich)"
                },
                {
                  "es": "El presidente, que fuera elegido en 2020...",
                  "en": "que fue elegido... — Der Präsident, der 2020 gewählt wurde... (journalistisch)"
                },
                {
                  "es": "Hubiera sido mejor no decir nada.",
                  "en": "Habría sido mejor... — Es wäre besser gewesen, nichts zu sagen."
                }
              ]
            }
          ]
        },
        {
          "id": "2.3",
          "title": "Das Pretérito Anterior (Hubo + Participio)",
          "blocks": [
            {
              "type": "text",
              "content": "Das Pretérito Anterior ist eine archaische Zeitform, die im literarischen Spanisch fortbesteht. Es drückt eine Handlung aus, die unmittelbar vor einer anderen vergangenen Handlung abgeschlossen wurde."
            },
            {
              "type": "text",
              "content": "Bildung: Indefinido von haber + Participio (Partizip)"
            },
            {
              "type": "table",
              "headers": [
                "Person",
                "Form"
              ],
              "rows": [
                [
                  "yo",
                  "hube hablado"
                ],
                [
                  "tú",
                  "hubiste hablado"
                ],
                [
                  "él/ella/usted",
                  "hubo hablado"
                ],
                [
                  "nosotros/as",
                  "hubimos hablado"
                ],
                [
                  "vosotros/as",
                  "hubisteis hablado"
                ],
                [
                  "ellos/ellas/ustedes",
                  "hubieron hablado"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "Fast ausschließlich in formellen Texten und Literatur zu finden",
                "Verwendung nach temporalen Konjunktionen: en cuanto, apenas, tan pronto como, después de que, una vez que",
                "In der modernen Sprache ersetzt man es durch das Pluscuamperfecto oder das einfache Indefinido"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Apenas hubo terminado, se marchó.",
                  "en": "Kaum war er fertig, ging er."
                },
                {
                  "es": "En cuanto hubo recibido la noticia, llamó a su familia.",
                  "en": "Sobald er die Nachricht erhalten hatte, rief er seine Familie an."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 2,
      "title": "Erweiterte Satzstrukturen",
      "sections": [
        {
          "id": "3.1",
          "title": "Absolute Konstruktionen mit dem Participio",
          "blocks": [
            {
              "type": "text",
              "content": "Das Participio kann einen Nebensatz mit einer absoluten Konstruktion einleiten, die im Deutschen \"nachdem/als/da ... + Partizip\" entspricht."
            },
            {
              "type": "text",
              "content": "Struktur: Participio (in Kongruenz mit dem Substantiv) + Substantiv + Hauptsatz"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Terminada la reunión, todos se fueron.",
                  "en": "Nachdem das Treffen beendet war, gingen alle."
                },
                {
                  "es": "Una vez resuelto el problema, pudimos continuar.",
                  "en": "Sobald das Problem gelöst war, konnten wir fortfahren."
                },
                {
                  "es": "Dicho esto, pasemos a otro tema.",
                  "en": "Nachdem das gesagt ist, kommen wir zu einem anderen Thema."
                },
                {
                  "es": "Vistas las pruebas, el juez dictó sentencia.",
                  "en": "Nach Einsicht in die Beweise fällte der Richter das Urteil."
                },
                {
                  "es": "Hechas las presentaciones, comenzó la cena.",
                  "en": "Nachdem man einander vorgestellt hatte, begann das Abendessen."
                }
              ]
            }
          ]
        },
        {
          "id": "3.2",
          "title": "Absolute Konstruktionen mit dem Gerundio",
          "blocks": [
            {
              "type": "text",
              "content": "Das Gerundio kann ebenfalls absolute Konstruktionen bilden, die Art und Weise, Grund oder Gleichzeitigkeit ausdrücken."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Habiendo terminado el trabajo, se fue a casa.",
                  "en": "Nachdem er die Arbeit beendet hatte, ging er nach Hause."
                },
                {
                  "es": "Siendo ya tarde, decidimos irnos.",
                  "en": "Da es schon spät war, beschlossen wir zu gehen."
                },
                {
                  "es": "No habiendo otra opción, aceptó.",
                  "en": "Da es keine andere Option gab, akzeptierte er."
                }
              ]
            }
          ]
        },
        {
          "id": "3.3",
          "title": "Spaltsätze und Pseudo-Spaltsätze — fortgeschritten",
          "blocks": [
            {
              "type": "text",
              "content": "Spaltsätze (oraciones hendidas):"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Fue María la que lo descubrió.",
                  "en": "Es war Maria, die es entdeckte."
                },
                {
                  "es": "Es en invierno cuando más llueve.",
                  "en": "Im Winter regnet es am meisten."
                },
                {
                  "es": "Es por eso por lo que estoy aquí.",
                  "en": "Aus diesem Grund bin ich hier."
                }
              ]
            },
            {
              "type": "text",
              "content": "Pseudo-Spaltsätze (oraciones pseudohendidas):"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Lo que me preocupa es la economía.",
                  "en": "Was mich beunruhigt, ist die Wirtschaft."
                },
                {
                  "es": "Lo que hizo fue marcharse sin decir nada.",
                  "en": "Was er tat, war zu gehen, ohne etwas zu sagen."
                },
                {
                  "es": "Lo que necesitamos es más tiempo.",
                  "en": "Was wir brauchen, ist mehr Zeit."
                },
                {
                  "es": "A quien buscan es a ti.",
                  "en": "Wen sie suchen, bist du."
                }
              ]
            }
          ]
        },
        {
          "id": "3.4",
          "title": "Korrelative Strukturen",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Struktur",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "No solo... sino también",
                  "Nicht nur... sondern auch",
                  "No solo habla español, sino que también habla chino."
                ],
                [
                  "Cuanto más... más",
                  "Je mehr... desto mehr",
                  "Cuanto más estudio, más aprendo."
                ],
                [
                  "Cuanto menos... menos",
                  "Je weniger... desto weniger",
                  "Cuanto menos duermes, menos rindes."
                ],
                [
                  "Cuanto más... menos",
                  "Je mehr... desto weniger",
                  "Cuanto más habla, menos le escuchan."
                ],
                [
                  "Tanto... como",
                  "Sowohl... als auch",
                  "Tanto los profesores como los alumnos están de acuerdo."
                ],
                [
                  "Ni... ni",
                  "Weder... noch",
                  "Ni lo sé ni me importa."
                ],
                [
                  "O... o",
                  "Entweder... oder",
                  "O vienes ahora o te quedas."
                ],
                [
                  "Ya... ya / Bien... bien",
                  "Ob... oder / sei es... sei es",
                  "Ya llueva, ya haga sol, saldremos."
                ]
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 3,
      "title": "Stilistik und rhetorische Mittel",
      "sections": [
        {
          "id": "4.1",
          "title": "Rhetorische Fragen",
          "blocks": [
            {
              "type": "text",
              "content": "Fragen, die eher für den Effekt als zur Informationsbeschaffung verwendet werden."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¿Acaso no lo dije yo desde el principio?",
                  "en": "Habe ich es nicht von Anfang an gesagt?"
                },
                {
                  "es": "¿Quién no ha soñado alguna vez con viajar al espacio?",
                  "en": "Wer hat nicht schon einmal davon geträumt, ins All zu reisen?"
                },
                {
                  "es": "¿A quién le importa?",
                  "en": "Wen kümmert das schon?"
                },
                {
                  "es": "¿Y qué más da?",
                  "en": "Und was macht das schon aus?"
                }
              ]
            }
          ]
        },
        {
          "id": "4.2",
          "title": "Litotes (Untertreibung durch Verneinung)",
          "blocks": [
            {
              "type": "text",
              "content": "Etwas bejahen, indem man sein Gegenteil verneint."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "No es mala idea.",
                  "en": "Das ist keine schlechte Idee. (= das ist eine gute Idee)"
                },
                {
                  "es": "No es poco lo que ha conseguido.",
                  "en": "Was er erreicht hat, ist nicht wenig. (= es ist beeindruckend)"
                },
                {
                  "es": "No deja de tener razón.",
                  "en": "Er hat nicht unrecht. (= er hat recht)"
                },
                {
                  "es": "No me desagrada.",
                  "en": "Es missfällt mir nicht. (= es gefällt mir)"
                }
              ]
            }
          ]
        },
        {
          "id": "4.3",
          "title": "Hyperbaton (veränderte Wortstellung als Stilmittel)",
          "blocks": [
            {
              "type": "text",
              "content": "Das absichtliche Durchbrechen der normalen Wortstellung für literarische, poetische oder nachdrückliche Effekte."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Grande fue su sorpresa.",
                  "en": "Groß war seine Überraschung. (Adjektiv vorangestellt)"
                },
                {
                  "es": "Del salón en el ángulo oscuro...",
                  "en": "In der dunklen Ecke des Salons... (Bécquer)"
                },
                {
                  "es": "Triste estaba el rey.",
                  "en": "Traurig war der König."
                }
              ]
            }
          ]
        },
        {
          "id": "4.4",
          "title": "Ellipse und ausgelassene Elemente",
          "blocks": [
            {
              "type": "text",
              "content": "Auf C2-Niveau nutzt man Ellipsen frei und lässt Elemente weg, die sich aus dem Kontext erschließen."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¿Vienes? — Sí (vengo).",
                  "en": "Kommst du? — Ja (ich komme)."
                },
                {
                  "es": "Yo quiero café y ella (quiere) té.",
                  "en": "Ich möchte Kaffee und sie (möchte) Tee."
                },
                {
                  "es": "Antes vivía en Madrid; ahora, (vivo) en Barcelona.",
                  "en": "Früher lebte ich in Madrid; jetzt (lebe ich) in Barcelona."
                },
                {
                  "es": "Los más jóvenes bailaban; los más viejos, (se sentaban y) observaban.",
                  "en": "Die Jüngeren tanzten; die Älteren beobachteten."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 4,
      "title": "Modalität und Evidentialität",
      "sections": [
        {
          "id": "5.1",
          "title": "Grad der Gewissheit ausdrücken",
          "blocks": [
            {
              "type": "text",
              "content": "C2-Sprecher modulieren Gewissheit präzise."
            },
            {
              "type": "table",
              "headers": [
                "Grad",
                "Ausdruck",
                "Beispiel"
              ],
              "rows": [
                [
                  "Absolute Gewissheit",
                  "Es evidente / indudable / innegable que + ind.",
                  "Es innegable que ha mejorado."
                ],
                [
                  "Hohe Wahrscheinlichkeit",
                  "Seguramente / probablemente / sin duda",
                  "Seguramente ya ha llegado."
                ],
                [
                  "Mittlere Wahrscheinlichkeit",
                  "Es probable que + subj. / Posiblemente",
                  "Es probable que venga."
                ],
                [
                  "Geringe Wahrscheinlichkeit",
                  "Es poco probable que + subj. / Difícilmente",
                  "Es poco probable que apruebe."
                ],
                [
                  "Reine Möglichkeit",
                  "Puede que + subj. / Quizá(s) / Tal vez",
                  "Puede que tenga razón."
                ],
                [
                  "Spekulation (Gegenwart)",
                  "Futuro Simple (einfache Zukunft)",
                  "Tendrá unos cuarenta años."
                ],
                [
                  "Spekulation (Vergangenheit)",
                  "Condicional (Konditional)",
                  "Serían las tres."
                ],
                [
                  "Berichtete Information",
                  "Según / Al parecer / Se dice que",
                  "Al parecer, han llegado a un acuerdo."
                ],
                [
                  "Persönliche Meinung",
                  "A mi parecer / En mi opinión",
                  "A mi parecer, es una buena decisión."
                ],
                [
                  "Einschränkung",
                  "Que yo sepa / Hasta donde sé",
                  "Que yo sepa, no ha cambiado nada."
                ]
              ]
            }
          ]
        },
        {
          "id": "5.2",
          "title": "Quizá(s) / Tal vez / A lo mejor — Moduswahl",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Ausdruck",
                "Modus",
                "Beispiel"
              ],
              "rows": [
                [
                  "quizá(s) / tal vez",
                  "Indikativ (mehr Gewissheit) oder Subjuntivo (weniger Gewissheit)",
                  "Quizás viene. / Quizás venga."
                ],
                [
                  "a lo mejor",
                  "immer Indikativ",
                  "A lo mejor viene mañana."
                ],
                [
                  "posiblemente / probablemente",
                  "Indikativ oder Subjuntivo",
                  "Probablemente esté / está enfermo."
                ],
                [
                  "igual (umgangssprachlich)",
                  "Indikativ",
                  "Igual viene mañana."
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "\"A lo mejor\" steht NIEMALS im Subjuntivo (spanischer Konjunktiv), im Gegensatz zu \"quizás\" und \"tal vez\"."
              ]
            }
          ]
        },
        {
          "id": "5.3",
          "title": "Höflichkeit im Condicional — volles Spektrum",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Weniger höflich → Höflicher",
                "Beispiel"
              ],
              "rows": [
                [
                  "Quiero...",
                  "Quiero un café."
                ],
                [
                  "Querría...",
                  "Querría un café, por favor."
                ],
                [
                  "Quisiera...",
                  "Quisiera un café, por favor."
                ],
                [
                  "Me gustaría...",
                  "Me gustaría pedir un café."
                ],
                [
                  "¿Podría...?",
                  "¿Podría traerme un café?"
                ],
                [
                  "¿Sería tan amable de...?",
                  "¿Sería tan amable de traerme un café?"
                ],
                [
                  "¿Le importaría...?",
                  "¿Le importaría traerme un café?"
                ],
                [
                  "Si no es mucha molestia...",
                  "Si no es mucha molestia, ¿podría traerme un café?"
                ]
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 5,
      "title": "Komplexe indirekte Rede",
      "sections": [
        {
          "id": "6.1",
          "title": "Indirekte Rede mit mehreren Zeitverschiebungen",
          "blocks": [
            {
              "type": "text",
              "content": "In der erweiterten indirekten Rede können sich mehrere Zeiten gleichzeitig verschieben."
            },
            {
              "type": "text",
              "content": "Direkte Rede: \"Ayer fui al médico, me dijo que estaba bien, pero que debería hacer más ejercicio. Mañana empezaré.\""
            },
            {
              "type": "text",
              "content": "Indirekte Rede: Dijo que el día anterior había ido al médico, que le había dicho que estaba bien, pero que debería hacer más ejercicio. (Dijo) que al día siguiente empezaría."
            }
          ]
        },
        {
          "id": "6.2",
          "title": "Indirekte Rede mit Befehlen im Subjuntivo (spanischer Konjunktiv)",
          "blocks": [
            {
              "type": "text",
              "content": "Befehle, Bitten und Vorschläge in der indirekten Rede verwenden immer den Subjuntivo."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "\"Estudia más.\" → Le dijo que estudiara más.",
                  "en": "Direkter Befehl, wiedergegeben mit dem Subjuntivo"
                },
                {
                  "es": "\"No hables tan alto.\" → Le pidió que no hablara tan alto.",
                  "en": "Negativer Befehl, wiedergegeben mit dem Subjuntivo"
                },
                {
                  "es": "\"Sería mejor que descansaras.\" → Le sugirió que descansara.",
                  "en": "Vorschlag, wiedergegeben mit dem Subjuntivo"
                },
                {
                  "es": "\"¡Ojalá vengas!\" → Expresó su deseo de que viniera.",
                  "en": "Wunsch, wiedergegeben mit dem Subjuntivo"
                }
              ]
            }
          ]
        },
        {
          "id": "6.3",
          "title": "Wiedergabeverben — erweitertes Inventar",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Verb",
                "Register",
                "Nuance"
              ],
              "rows": [
                [
                  "manifestar",
                  "formal",
                  "äußern / erklären"
                ],
                [
                  "aseverar",
                  "formal",
                  "versichern / behaupten"
                ],
                [
                  "alegar",
                  "formal/juristisch",
                  "geltend machen / vorbringen"
                ],
                [
                  "matizar",
                  "formal",
                  "nuancieren / einschränken"
                ],
                [
                  "apostillar",
                  "formal",
                  "hinzufügen / anmerken"
                ],
                [
                  "recalcar",
                  "neutral",
                  "hervorheben"
                ],
                [
                  "insinuar",
                  "neutral",
                  "andeuten / insinuieren"
                ],
                [
                  "reprochar",
                  "neutral",
                  "vorwerfen"
                ],
                [
                  "lamentarse de que",
                  "neutral",
                  "bedauern"
                ],
                [
                  "jactarse de que",
                  "neutral",
                  "prahlen"
                ],
                [
                  "advertir",
                  "neutral",
                  "warnen"
                ],
                [
                  "recriminar",
                  "neutral",
                  "vorwerfen / tadeln"
                ]
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 6,
      "title": "Dialektale Variation",
      "sections": [
        {
          "id": "7.1",
          "title": "Voseo",
          "blocks": [
            {
              "type": "text",
              "content": "\"Vos\" ersetzt \"tú\" in Argentinien, Uruguay, Paraguay sowie in Teilen von Zentralamerika und Kolumbien. Die Verbformen weichen ab."
            },
            {
              "type": "text",
              "content": "Das Presente (Präsens) im Indikativ — Formen mit vos:"
            },
            {
              "type": "table",
              "headers": [
                "Standard (tú)",
                "Voseo (vos)"
              ],
              "rows": [
                [
                  "hablas",
                  "hablás"
                ],
                [
                  "comes",
                  "comés"
                ],
                [
                  "vives",
                  "vivís"
                ],
                [
                  "tienes",
                  "tenés"
                ],
                [
                  "puedes",
                  "podés"
                ],
                [
                  "quieres",
                  "querés"
                ],
                [
                  "vienes",
                  "venís"
                ],
                [
                  "dices",
                  "decís"
                ],
                [
                  "eres",
                  "sos"
                ]
              ]
            },
            {
              "type": "text",
              "content": "Der Imperativo (Befehlsform) — Formen mit vos:"
            },
            {
              "type": "table",
              "headers": [
                "Standard (tú)",
                "Voseo (vos)"
              ],
              "rows": [
                [
                  "habla",
                  "hablá"
                ],
                [
                  "come",
                  "comé"
                ],
                [
                  "vive",
                  "viví"
                ],
                [
                  "ven",
                  "vení"
                ],
                [
                  "di",
                  "decí"
                ],
                [
                  "sal",
                  "salí"
                ]
              ]
            },
            {
              "type": "rules",
              "items": [
                "Voseo ist in Argentinien und Uruguay Standard und angesehen",
                "In anderen Regionen ist es möglicherweise informell oder regional",
                "Negative Befehle greifen oft auf tú-Formen zurück: \"No hablés\" (in einigen Regionen) oder \"No hables\" (in anderen)"
              ]
            }
          ]
        },
        {
          "id": "7.2",
          "title": "Seseo, Ceceo und Distinción",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Muster",
                "Wo",
                "Beschreibung"
              ],
              "rows": [
                [
                  "Distinción",
                  "Nord- und Zentralspanien",
                  "\"c\" (vor e/i) und \"z\" = /θ/ (wie englisches \"th\"); \"s\" = /s/"
                ],
                [
                  "Seseo",
                  "Lateinamerika, Kanarische Inseln, Teile Südspaniens",
                  "\"c\" (vor e/i), \"z\" und \"s\" werden alle als /s/ ausgesprochen"
                ],
                [
                  "Ceceo",
                  "Einige Teile Südspaniens",
                  "\"c\" (vor e/i), \"z\" und \"s\" werden alle als /θ/ ausgesprochen"
                ]
              ]
            }
          ]
        },
        {
          "id": "7.3",
          "title": "Leísmo, Laísmo, Loísmo",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Phänomen",
                "Was passiert",
                "Region",
                "Akzeptanz"
              ],
              "rows": [
                [
                  "Leísmo",
                  "\"le\" wird als direktes Objekt (Akkusativobjekt) für männliche Personen verwendet",
                  "Zentralspanien",
                  "Von der RAE akzeptiert (für maskuline Singularpersonen)"
                ],
                [
                  "Laísmo",
                  "\"la\" wird als indirektes Objekt (Dativobjekt) für weibliche Personen verwendet",
                  "Teile von Zentralspanien",
                  "Nicht von der RAE akzeptiert"
                ],
                [
                  "Loísmo",
                  "\"lo\" wird als indirektes Objekt (Dativobjekt) für männliche Personen verwendet",
                  "Sehr begrenzte Gebiete",
                  "Nicht von der RAE akzeptiert"
                ]
              ]
            }
          ]
        },
        {
          "id": "7.4",
          "title": "Ustedes vs. Vosotros",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Region",
                "Informeller Plural (dt. \"ihr\")",
                "Formeller Plural (dt. \"Sie\")"
              ],
              "rows": [
                [
                  "Spanien",
                  "vosotros/as",
                  "ustedes"
                ],
                [
                  "Lateinamerika",
                  "ustedes",
                  "ustedes"
                ]
              ]
            }
          ]
        },
        {
          "id": "7.5",
          "title": "Das Pretérito Perfecto (Perfekt) vs. das Indefinido (einfache Vergangenheit)",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Region",
                "\"Hoy he comido paella.\"",
                "\"Hoy comí paella.\""
              ],
              "rows": [
                [
                  "Spanien (meistens)",
                  "Wird für Ereignisse am selben Tag bevorzugt",
                  "Weniger gebräuchlich für den heutigen Tag"
                ],
                [
                  "Lateinamerika (meistens)",
                  "Weniger gebräuchlich",
                  "Wird selbst für den heutigen Tag bevorzugt"
                ]
              ]
            }
          ]
        },
        {
          "id": "7.6",
          "title": "Diminutive — Regionale Variation",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Suffix",
                "Region",
                "Beispiel"
              ],
              "rows": [
                [
                  "-ito/a",
                  "Überall Standard",
                  "casita, perrito"
                ],
                [
                  "-ico/a",
                  "Kolumbien, Costa Rica, Aragon",
                  "momentico, ratico"
                ],
                [
                  "-illo/a",
                  "Südspanien",
                  "pueblecillo"
                ],
                [
                  "-iño/a",
                  "Galicien",
                  "pocoiño"
                ],
                [
                  "-ín/a",
                  "Asturien, León",
                  "pequeñín"
                ]
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 7,
      "title": "Nominalisierung und fortgeschrittene Wortbildung",
      "sections": [
        {
          "id": "8.1",
          "title": "Lo + Adjektiv (Nominalisierung)",
          "blocks": [
            {
              "type": "text",
              "content": "\"Lo\" + Adjektiv bildet ein abstraktes Substantiv — im Deutschen das substantivierte Adjektiv: \"das Gute\", \"das Wichtige\", also \"das, was ... ist\"."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Lo importante es la salud.",
                  "en": "Das Wichtige ist die Gesundheit."
                },
                {
                  "es": "Lo bueno de vivir aquí es el clima.",
                  "en": "Das Gute am Leben hier ist das Klima."
                },
                {
                  "es": "Lo peor ha pasado.",
                  "en": "Das Schlimmste ist vorbei."
                },
                {
                  "es": "Lo difícil es empezar.",
                  "en": "Das Schwierige ist anzufangen."
                },
                {
                  "es": "No sabes lo cansado que estoy.",
                  "en": "Du weißt nicht, wie müde ich bin."
                },
                {
                  "es": "Admiro lo bien que habla.",
                  "en": "Ich bewundere, wie gut sie spricht."
                }
              ]
            }
          ]
        },
        {
          "id": "8.2",
          "title": "Lo + Adverb / Lo + de",
          "blocks": [
            {
              "type": "text",
              "content": "Lo + Adverb:"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Lo bien que cocina es impresionante.",
                  "en": "Wie gut sie kocht, ist beeindruckend."
                },
                {
                  "es": "No imaginas lo rápido que pasó el tiempo.",
                  "en": "Du kannst dir nicht vorstellen, wie schnell die Zeit verging."
                }
              ]
            },
            {
              "type": "text",
              "content": "Lo de (die Sache mit / das mit ...):"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Lo de ayer fue un malentendido.",
                  "en": "Das von gestern war ein Missverständnis."
                },
                {
                  "es": "¿Qué sabes de lo de Juan?",
                  "en": "Was weißt du über die Sache mit Juan?"
                },
                {
                  "es": "Lo de siempre.",
                  "en": "Das Übliche."
                }
              ]
            }
          ]
        },
        {
          "id": "8.3",
          "title": "Fortgeschrittene Suffixe und Ableitung",
          "blocks": [
            {
              "type": "text",
              "content": "Vergrößerungsformen (Augmentativa):"
            },
            {
              "type": "table",
              "headers": [
                "Suffix",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "-azo/a",
                  "groß / eindrucksvoll / Schlag",
                  "cochazo (tolles Auto), portazo (Türknallen)"
                ],
                [
                  "-ón/ona",
                  "groß / vergrößernd",
                  "casona (großes Haus), solterón (eingefleischter Junggeselle)"
                ],
                [
                  "-ote/a",
                  "groß (manchmal pejorativ)",
                  "grandote (riesig), amigote (guter Kumpel)"
                ]
              ]
            },
            {
              "type": "text",
              "content": "Abwertende Formen (Pejorativa):"
            },
            {
              "type": "table",
              "headers": [
                "Suffix",
                "Bedeutung",
                "Beispiel"
              ],
              "rows": [
                [
                  "-ucho/a",
                  "schäbig / schlechte Qualität",
                  "casucha (Bruchbude), periodicucho (Käseblatt)"
                ],
                [
                  "-ejo/a",
                  "leicht abwertend",
                  "animalejo (kleines Viech), librejo (Schundbuch)"
                ],
                [
                  "-astro/a",
                  "Beziehung (abwertend)",
                  "madrastra (Stiefmutter), poetastro (Dichterling)"
                ]
              ]
            },
            {
              "type": "text",
              "content": "Verben aus Substantiven/Adjektiven:"
            },
            {
              "type": "table",
              "headers": [
                "Muster",
                "Beispiel"
              ],
              "rows": [
                [
                  "-izar",
                  "modernizar, legalizar, hospitalizar"
                ],
                [
                  "-ificar",
                  "simplificar, intensificar, clasificar"
                ],
                [
                  "-ear",
                  "golpear (schlagen), pasear (spazieren gehen), teclear (tippen)"
                ],
                [
                  "en-...-ar",
                  "engordar (dick machen), enfriar (abkühlen), endurecer (härten)"
                ],
                [
                  "a-...-ar",
                  "agrupar (gruppieren), acomodar (unterbringen)"
                ]
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 8,
      "title": "Pragmatik und kommunikative Funktionen",
      "sections": [
        {
          "id": "9.1",
          "title": "Zustimmung und Widerspruch ausdrücken",
          "blocks": [
            {
              "type": "text",
              "content": "Zustimmung (von schwach bis stark):"
            },
            {
              "type": "rules",
              "items": [
                "Bueno, sí... / Puede ser... / Tienes razón...",
                "Desde luego / Sin duda / Por supuesto",
                "Totalmente de acuerdo / No podría estar más de acuerdo"
              ]
            },
            {
              "type": "text",
              "content": "Teilweise Zustimmung:"
            },
            {
              "type": "rules",
              "items": [
                "Sí, pero...",
                "En parte tienes razón, pero...",
                "Es cierto que..., sin embargo...",
                "Hasta cierto punto, sí, pero..."
              ]
            },
            {
              "type": "text",
              "content": "Widerspruch (von schwach bis stark):"
            },
            {
              "type": "rules",
              "items": [
                "No estoy del todo de acuerdo...",
                "No lo veo así... / Permíteme discrepar...",
                "No comparto esa opinión / Con todos los respetos, creo que...",
                "Me temo que no puedo estar de acuerdo / Lamento discrepar, pero..."
              ]
            }
          ]
        },
        {
          "id": "9.2",
          "title": "Vermutungen und Hypothesen ausdrücken",
          "blocks": [
            {
              "type": "text",
              "content": "Über die Gegenwart:"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Estará en casa.",
                  "en": "Er ist wahrscheinlich zu Hause."
                },
                {
                  "es": "Puede que esté enfermo.",
                  "en": "Er ist möglicherweise krank."
                },
                {
                  "es": "A lo mejor tiene razón.",
                  "en": "Vielleicht hat er Recht."
                },
                {
                  "es": "Supongo que vendrá.",
                  "en": "Ich nehme an, er wird kommen."
                },
                {
                  "es": "Me imagino que estará cansado.",
                  "en": "Ich kann mir vorstellen, dass er müde ist."
                }
              ]
            },
            {
              "type": "text",
              "content": "Über die Vergangenheit:"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Habría salido antes de la tormenta.",
                  "en": "Er muss vor dem Sturm aufgebrochen sein."
                },
                {
                  "es": "Puede que no lo supiera.",
                  "en": "Er hat es vielleicht nicht gewusst."
                },
                {
                  "es": "Debió de ser difícil.",
                  "en": "Das muss schwierig gewesen sein."
                }
              ]
            }
          ]
        },
        {
          "id": "9.3",
          "title": "Grund, Zweck und Folge ausdrücken – Vertiefung",
          "blocks": [
            {
              "type": "text",
              "content": "Grund (weil):"
            },
            {
              "type": "rules",
              "items": [
                "porque / ya que / puesto que / dado que / visto que / en vista de que / habida cuenta de que / a causa de que / debido a que"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Habida cuenta de las circunstancias, no tuvimos otra opción.",
                  "en": "Angesichts der Umstände hatten wir keine andere Wahl."
                }
              ]
            },
            {
              "type": "text",
              "content": "Zweck (damit):"
            },
            {
              "type": "rules",
              "items": [
                "para que + subj. / a fin de que + subj. / con el objeto de que + subj. / con vistas a que + subj. / de modo que + subj. (Zweck) / de manera que + subj. (Zweck)"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Lo organizaron con vistas a que todos pudieran participar.",
                  "en": "Sie haben es so organisiert, dass alle teilnehmen konnten."
                }
              ]
            },
            {
              "type": "text",
              "content": "Folge (sodass – Resultat):"
            },
            {
              "type": "rules",
              "items": [
                "de modo que + ind. / de manera que + ind. / de tal forma que / de ahí que + subj. / hasta tal punto que"
              ]
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Llovió tanto que se inundó la calle.",
                  "en": "Es hat so viel geregnet, dass die Straße überschwemmt wurde."
                },
                {
                  "es": "Trabajó hasta tal punto que enfermó.",
                  "en": "Er hat so sehr gearbeitet, dass er krank wurde."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 9,
      "title": "Texttypen und Register",
      "sections": [
        {
          "id": "10.1",
          "title": "Akademisches Register",
          "blocks": [
            {
              "type": "text",
              "content": "C2-Sprecher verfassen formelle akademische Prosa."
            },
            {
              "type": "text",
              "content": "Charakteristische Merkmale:"
            },
            {
              "type": "rules",
              "items": [
                "Unpersönliche Konstruktionen: \"Se ha demostrado que...\" / \"Cabe señalar que...\" / \"Conviene destacar que...\"",
                "Passiv: \"Ha sido ampliamente estudiado...\"",
                "Nominalstil (Nominalisierung): \"la realización del proyecto\" statt \"realizar el proyecto\"",
                "Abschwächung (Hedging): \"parece indicar\" / \"sugiere que\" / \"cabría afirmar que\"",
                "Formelle Konnektoren: \"No obstante\" / \"Asimismo\" / \"En lo que concierne a\" / \"Por consiguiente\""
              ]
            },
            {
              "type": "text",
              "content": "Beispieltext:"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "El presente estudio tiene como objetivo analizar las variables que inciden en el rendimiento académico. Tal y como se ha demostrado en investigaciones previas, factores como la motivación y el entorno socioeconómico desempeñan un papel determinante. No obstante, conviene señalar que los resultados obtenidos no son concluyentes, habida cuenta de las limitaciones metodológicas del estudio.",
                  "en": "Beispiel für formelle akademische Prosa, die unpersönliche Konstruktionen, Abschwächung und formelle Konnektoren veranschaulicht."
                }
              ]
            }
          ]
        },
        {
          "id": "10.2",
          "title": "Journalistisches Register",
          "blocks": [
            {
              "type": "text",
              "content": "Charakteristische Merkmale:"
            },
            {
              "type": "rules",
              "items": [
                "Passiv und unpersönliches se: \"Se espera que...\" / \"Se ha confirmado que...\"",
                "Indirekte Rede mit verschiedenen Wiedergabeverben: \"manifestó\" / \"declaró\" / \"recalcó\" / \"insinuó\"",
                "Historisches Präsens für mehr Lebendigkeit",
                "-ra-Form des Subjuntivo als Condicional: \"El acuerdo, que lograra grandes avances...\"",
                "Nominalphrasen: \"la toma de decisiones\" / \"el punto de inflexión\""
              ]
            }
          ]
        },
        {
          "id": "10.3",
          "title": "Literarisches Register",
          "blocks": [
            {
              "type": "text",
              "content": "Charakteristische Merkmale:"
            },
            {
              "type": "rules",
              "items": [
                "Hyperbaton: \"Triste y solitaria quedó la casa.\"",
                "Subjektiver Gebrauch von estar: \"Estaba la noche oscura y silenciosa.\"",
                "Futuro de Subjuntivo in Sprichwörtern: \"Adonde fueres, haz lo que vieres.\"",
                "Häufiger Gebrauch von Gerundio- und Partizipialkonstruktionen",
                "Pretérito anterior: \"Apenas hubo hablado, se arrepintió.\""
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 10,
      "title": "Fehleranfällige Bereiche auf C2-Niveau",
      "sections": [
        {
          "id": "11.1",
          "title": "Dequeísmo und Queísmo",
          "blocks": [
            {
              "type": "text",
              "content": "Dequeísmo (falsch): Das Hinzufügen von \"de\" vor \"que\", wo es nicht hingehört."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Incorrecto: \"Creo de que es verdad.\" → Correcto: \"Creo que es verdad.\"",
                  "en": "Entfernen des falschen \"de\""
                },
                {
                  "es": "Incorrecto: \"Pienso de que tiene razón.\" → Correcto: \"Pienso que tiene razón.\"",
                  "en": "Entfernen des falschen \"de\""
                }
              ]
            },
            {
              "type": "text",
              "content": "Queísmo (falsch): Das Weglassen von \"de\" vor \"que\", wo es erforderlich ist."
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Incorrecto: \"Me alegro que estés bien.\" → Correcto: \"Me alegro de que estés bien.\"",
                  "en": "Hinzufügen des erforderlichen \"de\""
                },
                {
                  "es": "Incorrecto: \"Estoy seguro que vendrá.\" → Correcto: \"Estoy seguro de que vendrá.\"",
                  "en": "Hinzufügen des erforderlichen \"de\""
                }
              ]
            },
            {
              "type": "rules",
              "items": [
                "Test: Ersetze den Nebensatz durch \"eso/algo\" — wenn \"de\" benötigt wird, behalte es bei.",
                "\"Me alegro de eso.\" → \"Me alegro de que...\" (\"de\" wird benötigt)",
                "\"Creo eso.\" → \"Creo que...\" (kein \"de\")"
              ]
            }
          ]
        },
        {
          "id": "11.2",
          "title": "Concordancia (Kongruenz) in komplexen Sätzen",
          "blocks": [
            {
              "type": "text",
              "content": "Subjekt-Verb-Kongruenz bei Kollektivsubstantiven:"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "La mayoría de los estudiantes aprobó/aprobaron.",
                  "en": "Sowohl Singular als auch Plural sind zulässig."
                },
                {
                  "es": "Un grupo de turistas visitó/visitaron el museo.",
                  "en": "Beide Formen sind zulässig."
                }
              ]
            },
            {
              "type": "rules",
              "items": [
                "Mit \"cada uno\": immer Singular: \"Cada uno de ellos tiene su opinión.\"",
                "Kongruenz mit \"uno de los que\": \"Es uno de los que más trabaja/trabajan.\" — Beide zulässig; der Plural wird leicht bevorzugt."
              ]
            }
          ]
        },
        {
          "id": "11.3",
          "title": "Ser vs. Estar — Letzte Feinheiten",
          "blocks": [
            {
              "type": "text",
              "content": "\"Ser listo\" vs. \"Estar listo\": Die meisten Adjektivpaare sind auf B2-Niveau gefestigt, aber C2 erfordert völlige Automatisierung."
            },
            {
              "type": "text",
              "content": "Estar + Adjektive, die normalerweise mit ser assoziiert werden (Überraschung/Veränderung):"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "¡Estás muy guapa!",
                  "en": "Du siehst großartig aus! (veränderter Zustand)"
                },
                {
                  "es": "La ciudad está muy cambiada.",
                  "en": "Die Stadt hat sich sehr verändert."
                }
              ]
            },
            {
              "type": "text",
              "content": "Ser mit Adjektiven des Typs \"estar\" zur Klassifizierung:"
            },
            {
              "type": "examples",
              "examples": [
                {
                  "es": "Eso es estar loco.",
                  "en": "Das heißt (so viel wie) verrückt sein. (definierend)"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": 11,
      "title": "Sprichwörter und fortgeschrittene Redewendungen",
      "sections": [
        {
          "id": "12.1",
          "title": "Gängige Sprichwörter (Refranes)",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Sprichwort",
                "Bedeutung"
              ],
              "rows": [
                [
                  "A buen entendedor, pocas palabras (bastan).",
                  "Einem Klugen reicht ein halbes Wort."
                ],
                [
                  "Más vale tarde que nunca.",
                  "Besser spät als nie."
                ],
                [
                  "No hay mal que por bien no venga.",
                  "Jedes Unglück hat auch sein Gutes."
                ],
                [
                  "En boca cerrada no entran moscas.",
                  "Reden ist Silber, Schweigen ist Gold."
                ],
                [
                  "Dime con quién andas y te diré quién eres.",
                  "Sag mir, mit wem du gehst, und ich sage dir, wer du bist."
                ],
                [
                  "A caballo regalado no le mires el diente.",
                  "Einem geschenkten Gaul schaut man nicht ins Maul."
                ],
                [
                  "El que mucho abarca, poco aprieta.",
                  "Wer zu viel auf einmal will, erreicht nichts."
                ],
                [
                  "Quien mucho duerme, poco aprende.",
                  "Wer viel schläft, lernt wenig."
                ],
                [
                  "No por mucho madrugar amanece más temprano.",
                  "Man kann nichts erzwingen."
                ],
                [
                  "Más vale prevenir que curar.",
                  "Vorsorge ist besser als Nachsorge."
                ],
                [
                  "A falta de pan, buenas son tortas.",
                  "In der Not schmeckt die Wurst auch ohne Brot."
                ],
                [
                  "Donde fueres, haz lo que vieres.",
                  "Andere Länder, andere Sitten."
                ]
              ]
            }
          ]
        },
        {
          "id": "12.2",
          "title": "Redewendungen — Fortgeschritten",
          "blocks": [
            {
              "type": "table",
              "headers": [
                "Redewendung",
                "Bedeutung"
              ],
              "rows": [
                [
                  "No tener pelos en la lengua",
                  "kein Blatt vor den Mund nehmen"
                ],
                [
                  "Estar en las nubes",
                  "mit den Gedanken woanders sein"
                ],
                [
                  "Dar en el clavo",
                  "den Nagel auf den Kopf treffen"
                ],
                [
                  "Meter la pata",
                  "ins Fettnäpfchen treten"
                ],
                [
                  "Tomar el pelo a alguien",
                  "jemanden auf den Arm nehmen"
                ],
                [
                  "Estar hasta las narices",
                  "die Nase voll haben"
                ],
                [
                  "No dar pie con bola",
                  "nichts auf die Reihe bekommen"
                ],
                [
                  "Quedarse en blanco",
                  "ein Blackout haben"
                ],
                [
                  "Dar la vuelta a la tortilla",
                  "den Spieß umdrehen"
                ],
                [
                  "Ir al grano",
                  "auf den Punkt kommen"
                ],
                [
                  "Ponerse las pilas",
                  "sich anstrengen"
                ],
                [
                  "Ser pan comido",
                  "ein Kinderspiel sein"
                ],
                [
                  "Costar un ojo de la cara",
                  "ein Vermögen kosten"
                ],
                [
                  "Echar una mano",
                  "unter die Arme greifen"
                ],
                [
                  "Dormir como un tronco",
                  "schlafen wie ein Murmeltier"
                ],
                [
                  "Estar como una cabra",
                  "verrückt sein"
                ],
                [
                  "Llover a cántaros",
                  "in Strömen regnen"
                ],
                [
                  "No tener ni pies ni cabeza",
                  "weder Hand noch Fuß haben"
                ]
              ]
            }
          ]
        }
      ]
    }
  ]
}
